### ISSUE TITLE
Investigate potential memory leak

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1010]
User reported pathfinder v0.5.1 being killed as OOM by the kernel.

It was running on a test small box (~2GB RAM), but inspection of production memory usage graph seems to indicate pathfinder growing in memory.

![image](https://user-images.githubusercontent.com/48352201/229871983-94e07549-dd4f-4e6e-828f-a72f3c14cd49.png)

Relevant `dmesg -T| grep -E -i -B100 'killed **process` log snippets:
```
[Sun Apr  2 02:49:59 2023] Tasks state (memory values in pages):
[Sun Apr  2 02:49:59 2023] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
[Sun Apr  2 02:49:59 2023] [ 306313]  1000 306313   265279   123941  1380352        0             0 pathfinder
[Sun Apr  2 02:49:59 2023] [ 306357]  1000 306357   147207    67410   724992        0             0 pathfinder_pyth
[Sun Apr  2 02:49:59 2023] [ 306362]  1000 306362   143596    63624   700416        0             0 pathfinder_pyth
[Sun Apr  2 02:49:59 2023] [ 306364]  1000 306364   139055    59163   647168        0             0 pathfinder_pyth
[Sun Apr  2 02:49:59 2023] [ 306367]  1000 306367   190023    78270   819200        0             0 pathfinder_pyth
...
[Sun Apr  2 02:49:59 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-5482.scope,task=pathfinder,pid=306313,uid=1000
[Sun Apr  2 02:49:59 2023] Out of memory: Killed process 306313 (pathfinder) total-vm:1061116kB, anon-rss:495764kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1348kB oom_score_adj:0
```

**Comment by sergey-melnychuk** [comment]
I'm going to look into this.

**Comment by sergey-melnychuk** [comment]
It might not be memory leak *per se*, but rather [heap fragmentation issue](https://www.youtube.com/watch?v=YB6LTaGRQJg).

**Comment by Mirko-von-Leipzig** [comment]
Hard to say I suppose. One possible approach is to replicate it locally and then try things. For example, maybe using jemalloc it gets fixed?

**Comment by sergey-melnychuk** [comment]
The log shows that pathfinder is using way less than 2G of RAM: `total-vm:1061116kB, anon-rss:495764kB`. This might not be caused by a memory leak in pathfinder, but by some other (ram-heavy?) processes being started on the VM.
