### ISSUE TITLE
poseidon_hash_single not overriden with starknet_pathfinder_crypto

### ISSUE THREAD

**Issue by FabijanC** [eqlabs/pathfinder#1054]
As per the documentation, only `poseidon_hash_many` is mentioned. What about `poseidon_hash_single`?

https://github.com/eqlabs/pathfinder/blob/c9b5c428753ce3b59fa039c516b1be4e7bd9733a/crates/stark_hash_python/README.md?plain=1#L13

**Comment by kkovaacs** [comment]
That particular function seems to be unused in `cairo-lang` (and pathfinder) so we don't have an implementation for it. Do you have an actual use case for that?

**Comment by FabijanC** [comment]
I also noticed there are no direct references to it, but perhaps it is used in a way that is not traceable by IDE?

But no, I don't have an actual use case for that.

**Comment by FabijanC** [comment]
I've heard from Starkware and apparently they only use `poseidon_hash_single` for testing, not in production (although the person telling me this didn't sound 100% sure). But it might be enough to close this issue if you don't want them to accumulate in this repo.

**Comment by Mirko-von-Leipzig** [comment]
> I've heard from Starkware and apparently they only use `poseidon_hash_single` for testing, not in production (although the person telling me this didn't sound 100% sure). But it might be enough to close this issue if you don't want them to accumulate in this repo.

Thanks for following-up! In an effort for code minimization etc, I think we'd prefer to not add it if not required.
