### ISSUE TITLE
why is the disk clogged at 20% per day after installing the note and how to fix it?

### ISSUE THREAD

**Issue by lich891** [eqlabs/pathfinder#1056]
why is the disk clogged at 20% per day after installing the note and how to fix it?

**Comment by Mirko-von-Leipzig** [comment]
What do you mean by clogged? Is it using 20% of the disk space, or is using 20% of the disk IO?

**Comment by sergey-melnychuk** [comment]
Closing the issue for now, please feel free to reopen and provide more details.
