### ISSUE TITLE
tracking issue: p2p mvp

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1068]
These are not meant to be mutually exclusive topics, but rather just starting points.

- [ ] #1069
- [ ] #1070
- [x] #1071
- [x] #1326
- [x] #1327
- [x] #1356 
- [x] #1357
- [x] #1328
- [x] #1329
- [ ] #1072
- [x] #1374 
- [x] #1375 
- [x] #1572 
- [x] #1573  
- [x] #1614 
- [x] #1615
- [x] #1655
- [x] #1668 
- [ ] #1671    
- [x] #1670

**Comment by kkovaacs** [comment]
Closing this in favor of our current issues & milestones.
