### ISSUE TITLE
try out NAT-hole punching, with various transports

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1070]
We've had some limited success with NAT-hole punching. Attempt some more using QUIC / TCP / UDP transports and figure out what it takes to get it working.

- local firewall settings - port forwarding + static ports for example
- relay node settings
- log difficulties so we can have a decent guide available for setting up a node

**Comment by kkovaacs** [comment]
Based on recent discussions we'll probably just not use DCUtR -- nodes will use a public IP or UPNP/NAT-PMP to create a port forward.
