### ISSUE TITLE
glue code between API sync expects & actual p2p layer

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1071]
The sync logic will expect to use something simpler than the raw p2p interface we currently have. For example, sync has no reason to know about p2p peer IDs, streams, or message chunking etc. It wants a more abstract API.

This issue revolves around adding the glue code to transform the p2p API to one more suited for sync.

Example API to target:
```rust
/// Returns a range of canonical block headers
async fn block_headers(&ctx: P2PContext, from: BlockNumber, to: BlockNumber) -> Result<Vec<BlockHeader>, Error>;
/// Returns the variable length data of a block (txs, receipts)
async fn block_bodies(&ctx: P2PContext, from: BlockNumber, to: BlockNumber) -> Result<Vec<BlockBody>, Error>;
async fn state_updates(&ctx: P2PContext, from: BlockNumber, to: BlockNumber) -> Result<Vec<StateUpdate>, Error>;

/// Receiver for newly gossip'd block headers.
type HeaderReceiver = Receiver<BlockHeader>;
// ... repeat for other relevant data as well (?) unclear what is needed here yet though.
// Maybe literally just repeated for block body and state update? Depends if they get gossip'd or not.
```

Note that this is just an example. Maybe you find a better abstraction(s).

**Comment by CHr15F0x** [comment]
Breaking up into sub tasks:

- [x] update proto files & depending code
- [ ] sync handlers
- [ ] hybrid p2p/gw client

**Comment by CHr15F0x** [comment]
This issue is becoming too big, will add new sub tasks to the main tracing issue.
