### ISSUE TITLE
RPC v0.3 release

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1094]
The RPC specification has officially release [version 0.3](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.3.0).

This is the tracking issue for any changes that we still require. Since our current v0.3 implementation was mostly based off of the release candidate and sprinkled with some changes from master, it is unclear how close we are to fully implementing it.

As such, step 1 should be to audit our implementation versus the speecification. Add any required changes to this issue.

**Comment by Perados** [comment]
Hi @Mirko-von-Leipzig , yes we require the transaction and block ones, we've been waiting on this for a while. Do you know what would be the ETA for these endpoints?

We are able to get traces from the public mainnet node like this: ```curl https://alpha-mainnet.starknet.io/feeder_gateway/get_block_traces\?blockNumber\=50``` but this seems to be a totaly different endpoint. Is there something similar that I could use with a node that uses pathfinder?

Thank you for your work! 🙇‍♂️

**Comment by Mirko-von-Leipzig** [comment]
We're blocked by progress in the starknet-in-rust project, so its difficult to give an accurate ETA for these endpoints. We can do it now with the old vm, but we will have to re-do it once starknet-in-rust is complete - which is why we are delaying. As mentioned we are also concerned about performance - it will be very slow.

Technically what you want to achieve is already possible using the `starknet_simulateTransaction` endpoint. However, its not very ergonomic. You would first have to fetch all the transaction you need, and then pass those in for simulation via `starknet_simulateTransaction`.

Are you running your own pathfinder node, or are you using public endpoints like infura, alchemy etc? We can consider rolling out these methods sooner than starknet-in-rust if its a big enough problem?

**Comment by Perados** [comment]
Hi @Mirko-von-Leipzig, I tried using the `starknet_simulateTransaction` in starknet.py endpoint but keep getting an error:

```
await full_node_client._client.call(
    method_name='simulateTransaction',
    params={"block_id": {"block_number": 808808}, "transactions": [{'type': 'INVOKE',
 'max_fee': '0x0a3b5840f4000',
 'version': '0x01',
 'signature': ['0x01',
  '0x06da0427cf4c47874ae7895f9e6dba7ea',
  '0x0da46248327cf144f743489af5bcd76b2',
  '0x048580c6ceb082d642424194795512e07',
  '0x08a205d84eab8b6271d5fb3bb0f792ea4'],
 'nonce': '0x05b',
 'sender_address': '0x058fdab03bfc73f14fdedbec63a847d88038910723635a6c736d35085ce1f04f',
 'calldata': ['0x01',
  '0x07537d29a9d967598efa3295d68dc52057ed5fea939f0c49e6438dc543df8d7b',
  '0x06c65cd1e600b109afe7ed83702496be6e61fcf4eea5d745582be849bee092b',
  '0x00',
  '0x00',
  '0x00']}], "simulation_flags": []}
)

ClientError: Client failed with code -32603: Execution failed: StarknetErrorCode.TRANSACTION_FAILED: Error at pc=0:10:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:228)
Unknown location (pc=0:214)

Error in the called contract (0x58fdab03....
```

We are using private endpoints from node providers. Any way to get trace data from these nodes would be highly appreciated.

Thank you!

**Comment by Mirko-von-Leipzig** [comment]
@Perados is this the transaction you're trying to trace `0x71be28db94c649499b34afe83890a10cf11f41e55597e00f742c5163af4ed24`? Or are you trying to simulate something different? I'm asking because the inputs are different to what you've provided to RPC - from starknet block 808809 (the one you're simulating):

Both `calldata` and `signatures` are different, but the nonce and block is correct so I imagine this is it..

```json
{
    "transaction_hash": "0x71be28db94c649499b34afe83890a10cf11f41e55597e00f742c5163af4ed24",
    "version": "0x1",
    "max_fee": "0x13b983bbcb000",
    "signature": [
        "0x1",
        "0xdaa502088d666f1025a66c5b5fa613f8",
        "0xa25b3a3232bd9d8070e7974d5ba560a7",
        "0x7f0b912bd87ab42f41988f5d124f13dc",
        "0x777055a7f12c54c63a4d19292b075bba"
    ],
    "nonce": "0x5b",
    "sender_address": "0x58fdab03bfc73f14fdedbec63a847d88038910723635a6c736d35085ce1f04f",
    "calldata": [
        "0x2",
        "0x7a816059304c8263f61b7c510c3d0d7c9db2c7c5005c8d97e3d1443625cf0d1",
        "0x219209e083275171774dab1df80982e9df2096516f06319c5c6d71ae0a8480c",
        "0x0",
        "0x3",
        "0x65970f3b69907d0f57e830e47ed5d24092f753a9e2d08896460bf7c8b6bfcec",
        "0x3da2537e9ae9661dce99aa73ea608a2764d743a80b3a142d3f5714a72df1404",
        "0x3",
        "0x4",
        "0x7",
        "0x65970f3b69907d0f57e830e47ed5d24092f753a9e2d08896460bf7c8b6bfcec",
        "0x29a2241af62c0000",
        "0x0",
        "0x29a2241af62c0000",
        "0x0",
        "0x58fdab03bfc73f14fdedbec63a847d88038910723635a6c736d35085ce1f04f",
        "0x3"
    ],
    "type": "INVOKE_FUNCTION"
}
```

**Comment by kkovaacs** [comment]
Pathfinder (when running with debug logs enabled, eg. `RUST_LOG=pathfinder=debug`) prints a slightly more detailed (not truncated) error message into its logs when running the `starknet_simulateTransaction` call:

```
2023-05-25T07:59:01 DEBUG rpc_method:ext_py_sim_tx:stderr: (500, {'code': <StarknetErrorCode.TRANSACTION_FAILED: 53>, 'message': 'Error at pc=0:10:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:228)\nUnknown location (pc=0:214)\n\nError in the called contract (0x58fdab03bfc73f14fdedbec63a847d88038910723635a6c736d35085ce1f04f):\nError message: Invalid signature.\nError at pc=0:3991:\nAn ASSERT_EQ instruction failed: 15239207283188840726017966 != 5404539650678684789745642.\nCairo traceback (most recent call last):\nUnknown location (pc=0:7889)\nUnknown location (pc=0:7851)\nError message: Signers: invalid signature\nUnknown location (pc=0:4826)\nUnknown location (pc=0:5034)\nUnknown location (pc=0:4946)'}) name="v0.3_starknet_simulateTransaction" pid=2644
```

That is, the transaction has an invalid signature. I've also tried running the transaction @Mirko-von-Leipzig mentioned above -- that one is using the very same account contract and signature validation works OK.
