### ISSUE TITLE
Moving database issue

### ISSUE THREAD

**Issue by surlebeat** [eqlabs/pathfinder#1136]
Hey there. Trying to move my pathfinder folder to an external drive. I stopped and removed the docker then reinstalled with --data-directory /media/bob/Toshiba/pathfinder in the end of the script. 

```
sudo docker run \
  --name pathfinder \
  --restart unless-stopped \
  --detach \
  -p 9545:9545 \
  --user "$(id -u):$(id -g)" \
  -e RUST_LOG=info \
  -e PATHFINDER_ETHEREUM_API_URL="https://goerli.infura.io/v3/<project-id>" \
  -v $HOME/pathfinder:/usr/share/pathfinder/data \
  eqlabs/pathfinder
--data-directory /media/bob/Toshiba/pathfinder

``` 

When I look at the log I get an error saying "Failed to create a file in /media/bob/Toshiba/pathfinder. Make sure the directory is write me by the user running pathfinder. 

Caused by: No such file or directory (os error 2)

I checked the file path, actually copied it from nautilus. 
I also checked permissions on the folder and all its files: read and write. 

Any idea how to solve that? Thanks!

**Comment by sergey-melnychuk** [comment]
I think the problem might be caused by `/media/bob/Toshiba/pathfinder` not being mounted as a volume (`-v`) for a container. You can try [ssh into container](https://phase2.github.io/devtools/common-tasks/ssh-into-a-container/) and create a file in the folder (e.g. `touch /media/bob/Toshiba/pathfinder/created.txt`) to double check.

**Comment by kkovaacs** [comment]
Please try something like this instead:

```
sudo docker run \
  --name pathfinder \
  --restart unless-stopped \
  --detach \
  -p 9545:9545 \
  --user "$(id -u):$(id -g)" \
  -e RUST_LOG=info \
  -e PATHFINDER_ETHEREUM_API_URL="https://goerli.infura.io/v3/<project-id>" \
  -v /media/bob/Toshiba/pathfinder:/usr/share/pathfinder/data \
  eqlabs/pathfinder
```

**Comment by surlebeat** [comment]
> I think the problem might be caused by `/media/bob/Toshiba/pathfinder` not being mounted as a volume (`-v`) for a container. You can try [ssh into container](https://phase2.github.io/devtools/common-tasks/ssh-into-a-container/) and create a file in the folder (e.g. `touch /media/bob/Toshiba/pathfinder/created.txt`) to double check.

Thanks. 

I'm getting this error:
`sudo docker run pathfinder touch /media/bob/Toshiba/pathfinder/created.txt
Unable to find image 'pathfinder:latest' locally
docker: Error response from daemon: pull access denied for pathfinder, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`
But when I previously tried to create a file with command line on the path, it worked, just not from the docker.

**Comment by surlebeat** [comment]
> Please try something like this instead:
> 
> ```
> sudo docker run \
>   --name pathfinder \
>   --restart unless-stopped \
>   --detach \
>   -p 9545:9545 \
>   --user "$(id -u):$(id -g)" \
>   -e RUST_LOG=info \
>   -e PATHFINDER_ETHEREUM_API_URL="https://goerli.infura.io/v3/<project-id>" \
>   -v /media/bob/Toshiba/pathfinder:/usr/share/pathfinder/data \
>   eqlabs/pathfinder
> ```

Thank you very much it worked !!!
