### ISSUE TITLE
Lookover the unicode support for class hashes

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1143]
Class hashes are dependent on json however the gateway's python implementation doesn't know how to handle unicode and escapes them (since it only supports ascii).

#1142 introduced a quick fix patch but given the haste involved in the process, we should ensure it is fully correct.

**Comment by xJonathanLEI** [comment]
In terms of performance, that PR added a string allocation and a copy, both of which could technically have been avoided.

**Comment by Mirko-von-Leipzig** [comment]
@xJonathanLEI already improved the algorithm used in [starknet-rs](https://github.com/xJonathanLEI/starknet-rs/pull/417), we should port it.
