### ISSUE TITLE
No module named 'pathfinder_worker' durring installation

### ISSUE THREAD

**Issue by bednarczyk9** [eqlabs/pathfinder#1189]
Hello, I received error message : E   ModuleNotFoundError: No module named 'pathfinder_worker' durring installation of my node on Ubuntu 22.04. I tried also on Debian and I have similar issue. Please find the attached logs. Can you help me with this issue, please?

 
`root@ubuntu:~# cd pathfinder/py
python3 -m venv .venv
source .venv/bin/activate
(.venv) root@ubuntu:~/pathfinder/py# PIP_REQUIRE_VIRTUALENV=true pip install --upgrade pip
PIP_REQUIRE_VIRTUALENV=true pip install -r requirements-dev.txt
Requirement already satisfied: pip in ./.venv/lib/python3.10/site-packages (23.1.2)
Requirement already satisfied: aiohttp==3.8.4 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 7)) (3.8.4)
Requirement already satisfied: aiosignal==1.3.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 11)) (1.3.1)
Requirement already satisfied: async-timeout==4.0.2 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 13)) (4.0.2)
Requirement already satisfied: attrs==23.1.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 15)) (23.1.0)
Requirement already satisfied: base58==2.1.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 20)) (2.1.1)
Requirement already satisfied: bitarray==2.7.6 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 22)) (2.7.6)
Requirement already satisfied: black==22.10.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 24)) (22.10.0)
Requirement already satisfied: build==0.10.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 26)) (0.10.0)
Requirement already satisfied: cachetools==5.3.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 28)) (5.3.0)
Requirement already satisfied: cairo-lang==0.12.0a0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 32)) (0.12.0a0)
Requirement already satisfied: certifi==2023.5.7 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 34)) (2023.5.7)
Requirement already satisfied: charset-normalizer==3.1.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 36)) (3.1.0)
Requirement already satisfied: click==8.1.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 40)) (8.1.3)
Requirement already satisfied: cytoolz==0.12.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 44)) (0.12.1)
Requirement already satisfied: ecdsa==0.18.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 48)) (0.18.0)
Requirement already satisfied: eth-abi==2.2.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 50)) (2.2.0)
Requirement already satisfied: eth-account==0.5.9 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 54)) (0.5.9)
Requirement already satisfied: eth-hash[pycryptodome]==0.5.2 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 56)) (0.5.2)
Requirement already satisfied: eth-keyfile==0.5.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 61)) (0.5.1)
Requirement already satisfied: eth-keys==0.3.4 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 63)) (0.3.4)
Requirement already satisfied: eth-rlp==0.2.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 67)) (0.2.1)
Requirement already satisfied: eth-typing==2.3.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 71)) (2.3.0)
Requirement already satisfied: eth-utils==1.9.5 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 77)) (1.9.5)
Requirement already satisfied: fastecdsa==2.3.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 86)) (2.3.0)
Requirement already satisfied: flake8==5.0.4 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 88)) (5.0.4)
Requirement already satisfied: frozendict==2.3.8 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 90)) (2.3.8)
Requirement already satisfied: frozenlist==1.3.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 92)) (1.3.3)
Requirement already satisfied: hexbytes==0.3.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 96)) (0.3.1)
Requirement already satisfied: idna==3.4 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 101)) (3.4)
Requirement already satisfied: iniconfig==2.0.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 105)) (2.0.0)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 107)) (0.8.0a2)
Requirement already satisfied: jsonschema==4.17.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 109)) (4.17.3)
Requirement already satisfied: lark==1.1.5 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 111)) (1.1.5)
Requirement already satisfied: lru-dict==1.2.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 113)) (1.2.0)
Requirement already satisfied: marshmallow==3.19.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 115)) (3.19.0)
Requirement already satisfied: marshmallow-dataclass==8.5.14 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 121)) (8.5.14)
Requirement already satisfied: marshmallow-enum==1.5.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 123)) (1.5.1)
Requirement already satisfied: marshmallow-oneofschema==3.0.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 125)) (3.0.1)
Requirement already satisfied: mccabe==0.7.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 127)) (0.7.0)
Requirement already satisfied: mpmath==1.3.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 129)) (1.3.0)
Requirement already satisfied: multiaddr==0.0.9 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 133)) (0.0.9)
Requirement already satisfied: multidict==6.0.4 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 135)) (6.0.4)
Requirement already satisfied: mypy-extensions==1.0.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 139)) (1.0.0)
Requirement already satisfied: netaddr==0.8.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 143)) (0.8.0)
Requirement already satisfied: numpy==1.25.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 145)) (1.25.0)
Requirement already satisfied: packaging==23.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 147)) (23.1)
Requirement already satisfied: parsimonious==0.8.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 152)) (0.8.1)
Requirement already satisfied: pathspec==0.11.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 154)) (0.11.1)
Requirement already satisfied: pip-tools==6.13.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 156)) (6.13.0)
Requirement already satisfied: pipdeptree==2.9.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 158)) (2.9.3)
Requirement already satisfied: platformdirs==3.8.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 160)) (3.8.0)
Requirement already satisfied: pluggy==1.2.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 162)) (1.2.0)
Requirement already satisfied: prometheus-client==0.17.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 164)) (0.17.0)
Requirement already satisfied: protobuf==3.19.5 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 166)) (3.19.5)
Requirement already satisfied: py==1.11.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 168)) (1.11.0)
Requirement already satisfied: pycodestyle==2.9.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 170)) (2.9.1)
Requirement already satisfied: pycryptodome==3.18.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 172)) (3.18.0)
Requirement already satisfied: pyflakes==2.5.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 176)) (2.5.0)
Requirement already satisfied: pyproject-hooks==1.0.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 178)) (1.0.0)
Requirement already satisfied: pyrsistent==0.19.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 180)) (0.19.3)
Requirement already satisfied: pytest==7.1.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 182)) (7.1.3)
Requirement already satisfied: pytest-asyncio==0.21.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 187)) (0.21.0)
Requirement already satisfied: pyyaml==6.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 189)) (6.0)
Requirement already satisfied: requests==2.31.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 191)) (2.31.0)
Requirement already satisfied: rlp==2.0.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 195)) (2.0.1)
Requirement already satisfied: six==1.16.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 199)) (1.16.0)
Requirement already satisfied: sympy==1.12 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 204)) (1.12)
Requirement already satisfied: tomli==2.0.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 206)) (2.0.1)
Requirement already satisfied: toolz==0.12.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 212)) (0.12.0)
Requirement already satisfied: typeguard==2.13.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 214)) (2.13.3)
Requirement already satisfied: typing-extensions==4.6.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 216)) (4.6.3)
Requirement already satisfied: typing-inspect==0.9.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 220)) (0.9.0)
Requirement already satisfied: urllib3==2.0.3 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 222)) (2.0.3)
Requirement already satisfied: varint==1.0.2 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 224)) (1.0.2)
Requirement already satisfied: web3==5.31.4 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 226)) (5.31.4)
Requirement already satisfied: websockets==9.1 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 230)) (9.1)
Requirement already satisfied: wheel==0.40.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 232)) (0.40.0)
Requirement already satisfied: yarl==1.9.2 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 234)) (1.9.2)
Requirement already satisfied: zstandard==0.20.0 in ./.venv/lib/python3.10/site-packages (from -r requirements-dev.txt (line 236)) (0.20.0)
Requirement already satisfied: pip>=22.2 in ./.venv/lib/python3.10/site-packages (from pip-tools==6.13.0->-r requirements-dev.txt (line 156)) (23.1.2)
Requirement already satisfied: setuptools in ./.venv/lib/python3.10/site-packages (from pip-tools==6.13.0->-r requirements-dev.txt (line 156)) (59.6.0)
(.venv) root@ubuntu:~/pathfinder/py# pytest
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.10.6, pytest-7.1.3, pluggy-1.2.0
rootdir: /root/pathfinder/py, configfile: setup.cfg
plugins: web3-5.31.4, typeguard-2.13.3, asyncio-0.21.0
asyncio: mode=strict
collected 0 items / 1 error

================================================================================================================== ERRORS ===================================================================================================================
___________________________________________________________________________________________ ERROR collecting tests/pathfinder_worker/test_call.py ___________________________________________________________________________________________
ImportError while importing test module '/root/pathfinder/py/tests/pathfinder_worker/test_call.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/pathfinder_worker/test_call.py:11: in <module>
    import pathfinder_worker.call as call
E   ModuleNotFoundError: No module named 'pathfinder_worker'
========================================================================================================== short test summary info ==========================================================================================================
ERROR tests/pathfinder_worker/test_call.py

(.venv) root@ubuntu:~/pathfinder/py# ls -a
.  ..  .gitignore  .pytest_cache  .venv  README.md  goerli.sqlite  pyproject.toml  requirements-dev.txt  setup.cfg  src  tests  tools

(.venv) root@ubuntu:~/pathfinder/py/tests# ls -a
.  ..  pathfinder_worker
(.venv) root@ubuntu:~/pathfinder/py/tests# cd pathfinder_worker/
(.venv) root@ubuntu:~/pathfinder/py/tests/pathfinder_worker# ls
__pycache__  sierra_account.cairo  sierra_account_starknet_format.json  sierra_class_definition.json  test_call.py

Requiemnts:

#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile --extra=dev --output-file=requirements-dev.txt --resolver=backtracking pyproject.toml
#
aiohttp==3.8.4
    # via
    #   cairo-lang
    #   web3
aiosignal==1.3.1
    # via aiohttp
async-timeout==4.0.2
    # via aiohttp
attrs==23.1.0
    # via
    #   aiohttp
    #   jsonschema
    #   pytest
base58==2.1.1
    # via multiaddr
bitarray==2.7.6
    # via eth-account
black==22.10.0
    # via pathfinder-worker (pyproject.toml)
build==0.10.0
    # via pip-tools
cachetools==5.3.0
    # via
    #   cairo-lang
    #   pathfinder-worker (pyproject.toml)
cairo-lang==0.12.0a0
    # via pathfinder-worker (pyproject.toml)
certifi==2023.5.7
    # via requests
charset-normalizer==3.1.0
    # via
    #   aiohttp
    #   requests
click==8.1.3
    # via
    #   black
    #   pip-tools
cytoolz==0.12.1
    # via
    #   eth-keyfile
    #   eth-utils
ecdsa==0.18.0
    # via cairo-lang
eth-abi==2.2.0
    # via
    #   eth-account
    #   web3
eth-account==0.5.9
    # via web3
eth-hash[pycryptodome]==0.5.2
    # via
    #   cairo-lang
    #   eth-utils
    #   web3
eth-keyfile==0.5.1
    # via eth-account
eth-keys==0.3.4
    # via
    #   eth-account
    #   eth-keyfile
eth-rlp==0.2.1
    # via
    #   eth-account
    #   web3
eth-typing==2.3.0
    # via
    #   eth-abi
    #   eth-keys
    #   eth-utils
    #   web3
eth-utils==1.9.5
    # via
    #   eth-abi
    #   eth-account
    #   eth-keyfile
    #   eth-keys
    #   eth-rlp
    #   rlp
    #   web3
fastecdsa==2.3.0
    # via cairo-lang
flake8==5.0.4
    # via pathfinder-worker (pyproject.toml)
frozendict==2.3.8
    # via cairo-lang
frozenlist==1.3.3
    # via
    #   aiohttp
    #   aiosignal
hexbytes==0.3.1
    # via
    #   eth-account
    #   eth-rlp
    #   web3
idna==3.4
    # via
    #   requests
    #   yarl
iniconfig==2.0.0
    # via pytest
ipfshttpclient==0.8.0a2
    # via web3
jsonschema==4.17.3
    # via web3
lark==1.1.5
    # via cairo-lang
lru-dict==1.2.0
    # via web3
marshmallow==3.19.0
    # via
    #   cairo-lang
    #   marshmallow-dataclass
    #   marshmallow-enum
    #   marshmallow-oneofschema
marshmallow-dataclass==8.5.14
    # via cairo-lang
marshmallow-enum==1.5.1
    # via cairo-lang
marshmallow-oneofschema==3.0.1
    # via cairo-lang
mccabe==0.7.0
    # via flake8
mpmath==1.3.0
    # via
    #   cairo-lang
    #   sympy
multiaddr==0.0.9
    # via ipfshttpclient
multidict==6.0.4
    # via
    #   aiohttp
    #   yarl
mypy-extensions==1.0.0
    # via
    #   black
    #   typing-inspect
netaddr==0.8.0
    # via multiaddr
numpy==1.25.0
    # via cairo-lang
packaging==23.1
    # via
    #   build
    #   marshmallow
    #   pytest
parsimonious==0.8.1
    # via eth-abi
pathspec==0.11.1
    # via black
pip-tools==6.13.0
    # via pathfinder-worker (pyproject.toml)
pipdeptree==2.9.3
    # via cairo-lang
platformdirs==3.8.0
    # via black
pluggy==1.2.0
    # via pytest
prometheus-client==0.17.0
    # via cairo-lang
protobuf==3.19.5
    # via web3
py==1.11.0
    # via pytest
pycodestyle==2.9.1
    # via flake8
pycryptodome==3.18.0
    # via
    #   eth-hash
    #   eth-keyfile
pyflakes==2.5.0
    # via flake8
pyproject-hooks==1.0.0
    # via build
pyrsistent==0.19.3
    # via jsonschema
pytest==7.1.3
    # via
    #   cairo-lang
    #   pathfinder-worker (pyproject.toml)
    #   pytest-asyncio
pytest-asyncio==0.21.0
    # via cairo-lang
pyyaml==6.0
    # via cairo-lang
requests==2.31.0
    # via
    #   ipfshttpclient
    #   web3
rlp==2.0.1
    # via
    #   eth-account
    #   eth-rlp
six==1.16.0
    # via
    #   ecdsa
    #   multiaddr
    #   parsimonious
sympy==1.12
    # via cairo-lang
tomli==2.0.1
    # via
    #   black
    #   build
    #   pyproject-hooks
    #   pytest
toolz==0.12.0
    # via cytoolz
typeguard==2.13.3
    # via cairo-lang
typing-extensions==4.6.3
    # via
    #   marshmallow-dataclass
    #   typing-inspect
typing-inspect==0.9.0
    # via marshmallow-dataclass
urllib3==2.0.3
    # via requests
varint==1.0.2
    # via multiaddr
web3==5.31.4
    # via
    #   cairo-lang
    #   pathfinder-worker (pyproject.toml)
websockets==9.1
    # via web3
wheel==0.40.0
    # via pip-tools
yarl==1.9.2
    # via aiohttp
zstandard==0.20.0
    # via pathfinder-worker (pyproject.toml)

# The following packages are considered to be unsafe in a requirements file:
# pip
# setuptools

`

**Comment by kkovaacs** [comment]
It seems you haven't run the following command from our [guide](https://github.com/eqlabs/pathfinder/blob/main/doc/install-from-source.md#python-setup):

```
PIP_REQUIRE_VIRTUALENV=true pip install -e .[dev]
```

Could you please check that running that command (after `pip install -r requirements-dev.txt`) helps?

**Comment by bednarczyk9** [comment]
It's working thank you very much :) 

> It seems you haven't run the following command from our [guide](https://github.com/eqlabs/pathfinder/blob/main/doc/install-from-source.md#python-setup):
> 
> ```
> PIP_REQUIRE_VIRTUALENV=true pip install -e .[dev]
> ```
> 
> Could you please check that running that command (after `pip install -r requirements-dev.txt`) helps?

It's working, thank you very much. You are amazing :)

**Comment by bednarczyk9** [comment]
Helped: PIP_REQUIRE_VIRTUALENV=true pip install -e .[dev]
