### ISSUE TITLE
Database version 14 too old to migrate - how to uninstall pathfinder

### ISSUE THREAD

**Issue by bednarczyk9** [eqlabs/pathfinder#1194]
Hello,

By mistake I installed very old version of pathfinder and after upgrade I receive error message that the database is old.

How can I uninstall pathinder and delete database without deletion other constainers in my system?

I saw few quistions this type without answer.

`Jul 05 20:21:48 debian systemd[1]: Started Starknet Node daemon.
Jul 05 20:21:48 debian bash[2066531]:     Finished release [optimized] target(s) in 0.57s
Jul 05 20:21:48 debian bash[2066531]:      Running `/root/pathfinder/target/release/pathfinder --ethereum.url 'https://eth-goerli.alchemyapi.io/v2/EjXk8goxblnmzfLh_TMNA5bP4Az8xIJG'`
Jul 05 20:21:48 debian bash[2066531]: 2023-07-05T20:21:48  INFO  Starting node. version="v0.6.3"
Jul 05 20:21:49 debian bash[2066531]: 2023-07-05T20:21:49 ERROR Database version is too old to migrate version=14 limit=30
Jul 05 20:21:49 debian bash[2066531]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Migrate database
Jul 05 20:21:49 debian bash[2066531]: Caused by:
Jul 05 20:21:49 debian bash[2066531]:     Database version 14 too old to migrate', crates/pathfinder/src/bin/pathfinder/main.rs:78:82
Jul 05 20:21:49 debian bash[2066531]: stack backtrace:
Jul 05 20:21:49 debian bash[2066531]:    0: rust_begin_unwind
Jul 05 20:21:49 debian bash[2066531]:              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
Jul 05 20:21:49 debian bash[2066531]:    1: core::panicking::panic_fmt
Jul 05 20:21:49 debian bash[2066531]:              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
Jul 05 20:21:49 debian bash[2066531]:    2: core::result::unwrap_failed
Jul 05 20:21:49 debian bash[2066531]:              at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/result.rs:1687:5
Jul 05 20:21:49 debian bash[2066531]:    3: core::result::Result<T,E>::unwrap
Jul 05 20:21:49 debian bash[2066531]:    4: pathfinder::main::{{closure}}
Jul 05 20:21:49 debian bash[2066531]:    5: tokio::runtime::park::CachedParkThread::block_on
Jul 05 20:21:49 debian bash[2066531]:    6: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
Jul 05 20:21:49 debian bash[2066531]:    7: tokio::runtime::runtime::Runtime::block_on
Jul 05 20:21:49 debian bash[2066531]:    8: pathfinder::main
Jul 05 20:21:49 debian bash[2066531]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jul 05 20:21:49 debian systemd[1]: starknetnoded.service: Main process exited, code=exited, status=101/n/a
Jul 05 20:21:49 debian systemd[1]: starknetnoded.service: Failed with result 'exit-code'.
`

**Comment by Mirko-von-Leipzig** [comment]
You can simply delete the database file -- the node will generate a new one on startup.

The database is called `mainnet.sqlite`, `testnet2.sqlite` or `goerli.sqlite` depending on what network you are running on.

How did you end up installing such an old version?
