### ISSUE TITLE
JSON-RPC API 0.4 support

### ISSUE THREAD

**Issue by kkovaacs** [eqlabs/pathfinder#1200]
The upcoming version 0.4 of the JSON-RPC API contains some incompatible changes that we should add:

Quoting from 0.4.0-rc1 notes these are the upcoming major changes:

- Added a new estimateMessageFee endpoint
- Invoke v0 tx fix: remove nonce and change sender_address to contract_address
- Add SKIP_FEE_CHARGE flag to simulateTransactions and remove the SKIP_EXECUTE flag. This endpoint is expected, when no flags are provided, to behave just like the real sequencer, making sure that the balance has sufficient funds and charging fee before moving on to the next tx (this is a change from the current existing behavior on Pathfinder, which followed from the existing pythonic implementation).
- If any of the txs fails/reverts, the response should be an error rather than a list of simulation results split status field which appears in receipts into finality_status and execution_status

------------------------------------------------

[Release candidate 2 diff ](https://github.com/starkware-libs/starknet-specs/compare/v0.3.0...v0.4.0-rc2)

------------------------------------------------

@Mirko-von-Leipzig: breaking down by method - each should be checked individually for safety from rc2:

- [x] #1253
- [x] #1254
- [x] #1255
- [x] #1256
- [x] #1257
- [x] #1258
- [x] #1259
- [x] #1260
- [x] #1261
- [x] #1262
- [x] #1263
- [x] #1264
- [x] #1265
- [x] #1266
- [x] #1267
- [x] #1268
- [x] #1269
- [x] #1270
- [x] #1271
- [x] #1272
- [x] #1273
- [x] #1274
- [x] #1275
- [x] #1276
- [x] #1277
- [x] #1283 

--------------------------------------------------

Possible additional work from spec [PR](https://github.com/starkware-libs/starknet-specs/pull/119/files) with more error codes.

--------------------------------------------------

- [x] #1305

**Comment by Mirko-von-Leipzig** [comment]
From the diff between [v0.3 and v0.4.0-rc1](https://github.com/starkware-libs/starknet-specs/compare/v0.3.0...v0.4.0-rc1):

- [x] `starknet_estimateMesssageFee` added
- [ ] `starknet_estimateMesssageFee` schema changes
- [ ] `INVOKE_TXN_V0` potential schema changes
- [ ] `INVOKE_TXN_V1` potential schema changes
- [ ] Receipt schema changes to include status and finality changes
- [ ] `starknet_simulateTransactions` renamed to plural, revert support, `SKIP_FEE_CHARGE` flag and `code_address` renamed to `class_hash`

**Comment by Mirko-von-Leipzig** [comment]
- [ ] RPC v0.4: starknet_addDeclareTransaction
- [ ] RPC v0.4: starknet_addDeployAccountTransaction
- [ ] RPC v0.4: starknet_addInvokeTransaction
- [ ] RPC v0.4: starknet_blockHashAndNumber
- [ ] RPC v0.4: starknet_blockNumber
- [ ] RPC v0.4: starknet_call
- [ ] RPC v0.4: starknet_chainId
- [ ] RPC v0.4: starknet_estimateFee
- [ ] RPC v0.4: starknet_getBlockWithTxHashes
- [ ] RPC v0.4: starknet_getBlockWithTxs
- [ ] RPC v0.4: starknet_getBlockTransactionCount
- [ ] RPC v0.4: starknet_getClass
- [ ] RPC v0.4: starknet_getClassAt
- [ ] RPC v0.4: starknet_getClassHashAt
- [ ] RPC v0.4: starknet_getNonce
- [ ] RPC v0.4: starknet_getStorageAt
- [ ] RPC v0.4: starknet_getTransactionByBlockIdAndIndex
- [ ] RPC v0.4: starknet_getTransactionByHash
- [ ] RPC v0.4: starknet_getTransactionReceipt
- [ ] RPC v0.4: starknet_pendingTransactions
- [ ] RPC v0.4: starknet_syncing
- [ ] RPC v0.4: starknet_getEvents
- [ ] RPC v0.4: starknet_getStateUpdate
- [ ] RPC v0.4: starknet_simulateTransaction
- [ ] RPC v0.4: starknet_estimateMessageFee

**Comment by Mirko-von-Leipzig** [comment]
Also should be noted that without starknet-in-rust we essentially cannot support execution of reverted txns yet.

**Comment by Mirko-von-Leipzig** [comment]
Official v0.4 specification has been released, need to check for any required diffs against it.
