### ISSUE TITLE
Insufficient fee estimated for declare transactions

### ISSUE THREAD

**Issue by xJonathanLEI** [eqlabs/pathfinder#1208]
There seems to be an issue with estimating fees for `DECLARE` transactions (both v1 and v2). This is causing https://github.com/xJonathanLEI/starkli/pull/10#issuecomment-1635164926.

Don't have time to provide a reproducer yet. Creating this issue for tracking first.

**Comment by Mirko-von-Leipzig** [comment]
afaik we haven't changed anything here at all. Wonder if this isn't a descrepency between the new blockifier used by the sequencer and the cairo-lang vm.. Will TAL

**Comment by Mirko-von-Leipzig** [comment]
We've managed to build a reproducer for a testnet txn and indeed cairo-lang and the sequencer produce different resource consumption leading to different gas consumed.

We've passed this along to the sequencer team. Will udpate once we know more.

**Comment by kkovaacs** [comment]
Reproduction steps: I've taken [this](https://testnet.starkscan.co/tx/0x056fc43343cd3fc1432b207d6d3f9d2794b84e7027a9790eaa93a80b5dff762c) transaction from testnet and transformed it into a JSON-RPC estimate request (see the [attached JSON](https://github.com/eqlabs/pathfinder/files/12048543/declare.json.gz) that contains the whole request).

```
pathfinder [main●●] % curl -s https://alpha4.starknet.io/feeder_gateway/get_transaction_receipt\?transactionHash\=0x056fc43343cd3fc1432b207d6d3f9d2794b84e7027a9790eaa93a80b5dff762c | jq .actual_fee
"0x398ce8d9ddc0"
pathfinder [main●●] % curl -s https://alpha4.starknet.io/feeder_gateway/get_transaction_receipt\?transactionHash\=0x056fc43343cd3fc1432b207d6d3f9d2794b84e7027a9790eaa93a80b5dff762c | jq .block_number
832159
pathfinder [main●●] % curl -s https://alpha4.starknet.io/feeder_gateway/get_block\?blockNumber\=832159 | jq .gas_price
"0x5f2a88cc0"
```

From the transaction receipt I see that the actual fee according to the sequencer was: 0x398ce8d9ddc0. The gas price for the block was 0x5f2a88cc0, so gas_consumed is 2477.

When doing the estimation with pathfinder (using cairo-lang 0.12.0a0):

```
~ % curl --json @declare.json http://localhost:8888/rpc/v0.3 
{"jsonrpc":"2.0","result":[{"gas_consumed":"0x4e5","gas_price":"0x5df7ba960","overall_fee":"0x1cbed84402e0"}],"id":"0"}%
```

That is, gas_consumed is 1253.
