### ISSUE TITLE
Add `/health` endpoint and return 200 for `/`

### ISSUE THREAD

**Issue by chichi13** [eqlabs/pathfinder#1218]
Hello,

We're using several instances of pathfinder / juno binaries for our Starknet RPCs.
The root path (`/`) of pathfinder return a 400 : 

```json
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```

Do you think it's possible to add a `/health` endpoint returning 200 if the binary is running well for our Load Balancer Health Check ? (on the `--http-rpc` port)
Furthermore, do you think it's possible to return `200` when there are no parameters given on the endpoint `/` please ?

**Comment by chichi13** [comment]
We have quite a few bots spamming the root path `/`, which triggers alerts from our monitoring system because it returns 4XX errors. To avoid this, returning `200` is a fairly common solution. If `/` returns a `200`, there's no need to add a `/health`.

Yes, I'm aware that the monitoring endpoint has a `/health`. However, for security reasons, the monitoring port is not open to everyone, so it's not open to Load Balancers (we don't have the IPs of these Load Balancers).

**Comment by Mirko-von-Leipzig** [comment]
Oh I see. Interesting. We purposefully separated monitoring from the public endpoints so that it wouldn't be exposed 😅 

Okay so if I understand correctly, simply returning `200` from `/` would solve your problem entirely?

**Comment by CHr15F0x** [comment]
FYI: https://github.com/eqlabs/pathfinder/pull/1241

@chichi13

I made the health check http verb agnostic as I'm not sure if the bots GET or POST on `/`.

>Furthermore, do you think it's possible to return 200 when there are no parameters given on the endpoint / please ?

I also assumed this means empty request body - am I right here?

**Comment by chichi13** [comment]
Thanks for the PR and the changes !

Bots generally only GET. But what you did seems to be exactly what was needed :)

> I also assumed this means empty request body - am I right here?

Yes exactly :)
