### ISSUE TITLE
RPC v0.4: starknet_simulateTransaction

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1276]

**Comment by kkovaacs** [comment]
Looks like the spec now has a `SKIP_FEE_CHARGE` flag that we currently _always_ do. We should probably document this but it's something that we should only implement with starknet_in_rust I guess...

**Comment by kkovaacs** [comment]
According to the specification [diff](https://github.com/starkware-libs/starknet-specs/compare/v0.3.0...v0.4.0-rc2#diff-dd950cbb7c4a2efb76af2439013e0b1c0fb95b7e0c0fad5113e42e4a45e9b470R1261-R1276) `FUNCTION_INVOCATION` had `code_address` renamed to `class_hash` -- so our output types should be changed accordingly.
