### ISSUE TITLE
Milestone 1 release

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#128]
Tracking for tasks remaining before the milestone 1 release.

- [x] Connection auto-retry
  - [x] #140
  - [x] #139
- [x] Sync process
  - [x] #134
  - [x] #136
  - [x] #135
  - [x] #137
  - [x] #138
  - [x] #147
- [x] RPC functionality
  - [x] #130
  - [x] #131
  - [x] #143
- [x] storage
  - [x] #132
- [x] #133

**Comment by CHr15F0x** [comment]
With the last item done we can mark this tracing issue finally closed.
