### ISSUE TITLE
[Documentation inconsistency]: MDS matrix

### ISSUE THREAD

**Issue by satoshiotomakan** [eqlabs/pathfinder#1292]
MDS matrix is different:
Comment: https://github.com/eqlabs/pathfinder/blob/36743e6a6d51addd8abb8c32149416548ee280d1/crates/stark_poseidon/src/poseidon.rs#L9-L10

Code generated from the constant:
> MDS = [[3, 1, 1], [1, -1, 1], [1, 1, -2]]
https://github.com/starkware-industries/poseidon/blob/5403dff9ff4eadb07deb5c0a43e88bedb011deb8/poseidon3.txt#L5

**Comment by Mirko-von-Leipzig** [comment]
Ah okay so just the `2` is missing a negation?

**Comment by satoshiotomakan** [comment]
@Mirko-von-Leipzig Yes, right
