### ISSUE TITLE
Outdated RPC example starknet_estimateFee

### ISSUE THREAD

**Issue by shadowpigy** [eqlabs/pathfinder#1334]
https://github.com/eqlabs/pathfinder/blob/15dcb46dba8d2466ef5415d1a6f92cb03d4e321c/doc/rpc/rpc_examples_v03.sh#L109

The example returns a failed response
`{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "invalid type: map, expected a sequence at line 2 column 19"
    },
    "id": "0"
}`

**Comment by CHr15F0x** [comment]
Good catch, thanks @shadowpigy
