### ISSUE TITLE
RPC incorrectly requires `debug_info` to be present for Cairo 0 class declaration

### ISSUE THREAD

**Issue by xJonathanLEI** [eqlabs/pathfinder#1371]
## Summary

Since v0.8.1, declaring Cairo 0 contract incorrectly requires `debug_info` to be present as part of the program. `debug_info` isn't _really_ used for declaration. There's no reason for `pathfinder` to require it.

## Steps to reproduce

Simply run this `curl` command on a `pathfinder` node running v0.8.1.

```console
curl http://your.rpc.node/rpc/v0.4 \
  -H "Content-Type: application/json" \
  -d '{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "starknet_estimateFee",
  "params": [
    [
      {
        "type": "DECLARE",
        "contract_class": {
          "program": "H4sIAAAAAAAC/5WPzQqDMBCE32XPIklPxVcpJURd2wWzCZu1FCTv3qiF9urcZphvf1bwqkL9opihu90b6BealfjrhhgSzSjuhZIpMnRgWntpLTQwevVH60msFVhLAzQiK01U60cQPLHLQ0xYWed26yqdhMIWmffV/Mlac07bJYITCvKAdTz7B0pd/Qv3V0r5AMLJpd3rAAAA",
          "entry_points_by_type": {
            "CONSTRUCTOR":[],
            "EXTERNAL":[],
            "L1_HANDLER":[]
          },
          "abi": []
        },
        "sender_address": "0xc90aa68ad17e1a31cda68cf3a3677d33df487dc072c607b5577dbc9c282cde",
        "max_fee": "0x0",
        "version": "0x1",
        "signature": [
          "0xdd4fc6e91150c7dc547bab4b4c11f467a0e7609707dbae41f0c35d23351f9b",
          "0x5ae98e644f2917de4a9ca0565e8516c179b6542dfd840539b1b1da16110ab71"
        ],
        "nonce": "0x2"
      }
    ],
    "pending"
  ]
}'
```

## Expected result

Since this class is a made up class, the fee estimation would fail. However, the request itself is complete and should pass initial validation.

## Actual result

`pathfinder` returns a _validation_ error:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32603,
    "message": "missing field `debug_info` at line 1 column 327"
  },
  "id": 1
}
```

**Comment by kkovaacs** [comment]
Thanks for the report!

Indeed, it looks like in `starknet_api` 0.4.1 [deprecated_contract_class::Program](https://docs.rs/starknet_api/0.4.1/starknet_api/deprecated_contract_class/struct.Program.html) _requires_ `debug_info` to be present for de-serialization to succeed.

We can probably work around that issue by adding an empty `debug_info` into the program if it's missing -- but ultimately it looks like this is something that's not quite correct in `starknet_api`?

**Comment by xJonathanLEI** [comment]
Yeah I guess an immediate workaround is simply to always fill an empty `debug_info` to make the internal structs happy. Tbh it's not the first time I encountered StarkWare crates asking for something only to immediately throw it away...

**Comment by kkovaacs** [comment]
Looks like the underlying starknet_api issue has already been fixed (but not released yet): https://github.com/starkware-libs/starknet-api/commit/f3f752d00598fce401b50d5e409e3e4c31c8924d
