### ISSUE TITLE
Tracing methods should try fetching trace from feeder gateway upon execution failure

### ISSUE THREAD

**Issue by kkovaacs** [eqlabs/pathfinder#1450]
Our execution engine is not guaranteed to be able to run all transactions from historic blocks. First of all, blockifier does not support DEPLOY transactions at all. Even if it would fee calculation changes could still cause issues because transaction costs could now exceed max fees set in transactions.

The feeder gateway has all historical traces in its database, so in the execution error cases above we should just fetch the trace from the gateway. We should implement this behavior for `starknet_traceBlockTransactions` and `starknet_traceTransaction`.

**Comment by Mirko-von-Leipzig** [comment]
Since we know DEPLOY aren't supported, it probably makes sense to identify those before even attempting to perform local execution.
