### ISSUE TITLE
RPC v0.5: traces now have required fields

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1459]
Our trace methods re-use the structs from v0.4 but several of the outputs are now required whereas before they were optional.

**Comment by kkovaacs** [comment]
Probably not a "real" difference: even where we have `Option<XXX>` in out RPC types our conversion code actually always uses `Some(XXX)` so we should just probably remove the options.

**Comment by Mirko-von-Leipzig** [comment]
Afaik this is not the case. At least @xJonathanLEI has found can return `None` i.e. are missing. From my brief read through the code I think we only map whatever the execution engine returns.

An example given is when skipping validation, then `validate_invocation` is not returned.

**Comment by kkovaacs** [comment]
OK, but in that case I think that's a specification issue. You can't return a trace if there's none?

**Comment by xJonathanLEI** [comment]
Can confirm that `fee_transfer_invocation` is always `None` when simulating txs, and `validate_invocation` is `None` when the skip validate flag is used (which makes sense).

**Comment by kkovaacs** [comment]
> Can confirm that `fee_transfer_invocation` is always None when simulating txs

Hmm, that definitely sounds like a bug -- and not something I'd expect based on our tests...

**Comment by kkovaacs** [comment]
@xJonathanLEI do you happen to have a test input for which you don't get a valid `fee_transfer_invocation` in `starknet_simulateTransaction` (without the `SKIP_FEE_TRANSFER` flag)?

**Comment by Mirko-von-Leipzig** [comment]
Fixed in spec, and pathfinder v0.9.5.
