### ISSUE TITLE
Fix release workflow

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1465]
We have an existing attempt at creating a [release workflow](https://github.com/eqlabs/pathfinder/blob/main/.github/workflows/release.yml), it is however horribly broken (⚠️ do not use it).

We should probably use https://github.com/taiki-e/create-gh-release-action; it looks like it ticks most of the boxes.

Rough requirements:

- manual trigger to specify the version
- sets the pathfinder package version correctly i.e. change the package version. lockfile probably also needs to be updated.
- creates a draft release with changelog details prefilled
- tags the release commit

**Comment by kkovaacs** [comment]
This has been implemented -- though somewhat differently. Pushing the tag is what triggers creating the draft release using the changelog.
