### ISSUE TITLE
RPC: Distinguish between internal errors and custom errors

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1467]
We currently use `InternalError` to handle both general request failures as well as custom errors which don't have a starknet RPC error type.

This is an issue as we don't want to surface real internal errors as this is a security risk, but we of course want to surface custom errors.

- create a new `Custom` error variant who's data does get output
- mute the internal error data
- log internal errors
- map all current custom usage to `Custom`

**Comment by pierre-l** [comment]
@Mirko-von-Leipzig That could be educational to me
