### ISSUE TITLE
Support V3 transactions in `starknet_gateway_types`

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1483]
Update the gateway's transaction schema to include the new V3 transaction types. ~The schema is not yet available.~ Schema examples below.

**Comment by kkovaacs** [comment]
We have the following example transactions as represented on the feeder gateway:

Declare:

`{"transaction_hash": "0x26a0997563e274e3de1d49a3c2d2b3bfcdfb3766c5ade47adf6db07f4a4bace", "version": "0x3", "signature": [], "nonce": "0x0", "nonce_data_availability_mode": 0, "fee_data_availability_mode": 0, "resource_bounds": {"L1_GAS": {"max_amount": "0x4000000000000", "max_price_per_unit": "0x4000000000000"}, "L2_GAS": {"max_amount": "0x0", "max_price_per_unit": "0x0"}}, "tip": "0x0", "paymaster_data": [], "sender_address": "0x11", "class_hash": "0x33645c3a0de0cb8f28f4a9ce1d355985650745f2c342d98405adf312e645bde", "compiled_class_hash": "0x17d1f05590d9668381eb2842f0e4d4096ac357924ec27857babbacbea70d45b", "account_deployment_data": [], "type": "DECLARE"}`

Deploy account:

`{"transaction_hash": "0x6841e1dd3542e0f27ebe95e4773a4ae84a7589001990a08a13b8e36e0ad4523", "version": "0x3", "signature": [], "nonce": "0x0", "nonce_data_availability_mode": 0, "fee_data_availability_mode": 0, "resource_bounds": {"L1_GAS": {"max_amount": "0x4000000000000", "max_price_per_unit": "0x4000000000000"}, "L2_GAS": {"max_amount": "0x0", "max_price_per_unit": "0x0"}}, "tip": "0x0", "paymaster_data": [], "sender_address": "0xdd52abb2d7546da6cb8dbf21df6ebccc573463df5789fa2febbd246cd82940", "contract_address_salt": "0x2", "class_hash": "0x1", "constructor_calldata": [], "type": "DEPLOY_ACCOUNT"}`

Invoke fucntion:

`{"transaction_hash": "0x77af1e6e8e6e9fe3c68aadae99e3e55b63321754d801c12122f937d12ff6893", "version": "0x3", "signature": ["0x1132577", "0x17df53c", "0x0"], "nonce": "0x0", "nonce_data_availability_mode": 0, "fee_data_availability_mode": 0, "resource_bounds": {"L1_GAS": {"max_amount": "0x4000000000000", "max_price_per_unit": "0x4000000000000"}, "L2_GAS": {"max_amount": "0x0", "max_price_per_unit": "0x0"}}, "tip": "0x0", "paymaster_data": [], "sender_address": "0x64", "calldata": ["0x0", "0x1", "0x2", "0x3", "0x4", "0x5", "0x6", "0x7", "0x8", "0x9"], "account_deployment_data": [], "type": "INVOKE_FUNCTION"}`

**Comment by kkovaacs** [comment]
And no changes on the receipt schema.
