### ISSUE TITLE
Reverse state trie updates

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1485]
Support the ability to undo the last `N` state updates wrt to the state trie. This will be required when a reorg exceeds the oldest stored state trie.

Rough overview to "reorg" the state trie to some target block `X` where `N` is the oldest stored state trie and `X < N`:

1. Start at the oldest stored state trie `N`
2. Collect all elements which changed in the range `T` where `X < T <= N`
3. For each unique change, assign it the value it would have had at block `X`
4. Apply the above changes to the state trie at `N`
5. Done

Note that changes may include the deletion or creation of an element.

**Comment by kkovaacs** [comment]
Implemented by PR #1854
