### ISSUE TITLE
RPC v0.5.1: `CallType::Delegate`

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1511]
RPC v0.5.1 added the `DELEGATE` call_type variant. We already (incorrectly) used this variant previously even though it didn't exist.

Audit our call_type implementation and ensure it is correct now wrt v0.5.1

**Comment by kkovaacs** [comment]
There's one more thing: blockifier always using DELEGATE is actually a bug in blockifier. In case that's fixed it will be possible to have _both_ DELEGATE and LIBRARY_CALL in a trace resulting from execution.

**Comment by Mirko-von-Leipzig** [comment]
## Additional info

If the caller is a cairo 1 class, then the blockifier DELEGATE should be mapped to LIBRARY_CALL.

Will update with cairo 0 decision once we have that info.

**Comment by kkovaacs** [comment]
Unfortunately it's not trivial to decide if the caller is a Cairo 1 class (We _do_ have the address but the class hash seems to be optional). It'd be probably much easier to handle this inside blockifier...

**Comment by kkovaacs** [comment]
Even if it's a new class we should be able to fetch it through the `CachedState` used to execute transactions. But all this is basically a non-trivial workaround for an issue blockifier has. I'd rather wait for a fix in blockifier than implementing this hack...
