### ISSUE TITLE
RPC v0.5.1: `validate_invocation` and `fee_transfer_invocation` are now optional

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1512]
As per title, these fields are now optional and should be marked as `None` if not present. This can occur if `SKIP_VALIDATE` or `SKIP_FEE` flags are set.

**Comment by kkovaacs** [comment]
What do you mean by
>  should be marked as None if not present?

As fare as I've seen these are already optional in our RPC output types (and we're skipping those properties on serialization if they're None).

**Comment by Mirko-von-Leipzig** [comment]
There are also several other optional changes in the spec diff for traces. We should audit these again.

**Comment by kkovaacs** [comment]
Yes. `state_diff` is now optional so we should simply skip that property instead of sending and empty state diff if we have no state diff (like for traces we've fetched from the gateway).
