### ISSUE TITLE
disk space problem on starknet node

### ISSUE THREAD

**Issue by Brtnnr** [eqlabs/pathfinder#1664]
hi.

i have been running starknet node for about 5 or 6 months. i had o reset the node once because my 1 tb ssd disk capacity didnt enough. the second node gets the same problem now. almost full capacity. please teel me how to reduce / prune disk. 

i followed theis guide : https://nunoynungning.medium.com/starknet-node-setup-guide-d5f0f9e8505c

thanks
<img width="960" alt="Ekran görüntüsü 2024-01-08 225730" src="https://github.com/eqlabs/pathfinder/assets/101182590/421c58af-a6c6-4a83-982e-10662bf51438">

**Comment by Mirko-von-Leipzig** [comment]
We don't as yet have a formal pruning tool. We are working on improving the situation in a few ways but it will take some time.

What do you use the node for? We could assist you with deleting some data manually.

For example, if you don't need old transaction data, then that could give you back around 30% of your disk for now?

**Comment by Brtnnr** [comment]
Hi. Thanks for reply.

İ am using raspberry pi 4 4gb with raspberry pi os.

**Comment by Mirko-von-Leipzig** [comment]
> Hi. Thanks for reply.
> 
> İ am using raspberry pi 4 4gb with raspberry pi os.

Do you use the RPC of the node at all? Or are you just running it for fun? 

What RPC methods do you use, if any?

**Comment by Brtnnr** [comment]
I set the Raspberry to start with 1 tb ssd, installed the operating system and applied the directives in the article above via putty. 

I also access and control it from everywhere with tailscale. Let's say I'm a bit curious about this kind of issues. Thats all.

**Comment by Mirko-von-Leipzig** [comment]
You can manually purge the event data (which is quite large). 

1. Ensure you have `sqlite3` available on your rpi. To install run: `sudo apt install sqlite3`.
2. Stop the node.
3. Test that everything is ok: `sqlite3 <path-to-pathfinder-database> "select number from block_headers limit 1;"` - this should print 0.
4. Delete the data: `sqlite3 <path-to-pathfinder-database> "delete * from starknet_events;"`

This will take quite a long time to run.

**Please be aware that after this you won't be able to query old event data from the node**
