### ISSUE TITLE
p2p: searching for peers should be a stream

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1696]
Discovering peers with a certain capability currently has to wait until the [entire search is completed](https://github.com/eqlabs/pathfinder/blob/main/crates/p2p/src/client/peer_aware.rs#L114-L118). This can take significant time.

Change this to output a stream of peers which would allow the caller to begin making progress without having to wait.

**Comment by CHr15F0x** [comment]
Not an issue right now as other node implementations don't use kad based capabilities and neither is pathfinder anymore.
