### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by sosedoff** [eqlabs/pathfinder#171]
The documentation states that OSX (M1 or x86) is not currently supported, however i was able to follow the readme and get everything installed with a small tweak to the `fastecdsa` package that was failing to compile.

```
CFLAGS=-I`brew --prefix gmp`/include LDFLAGS=-L`brew --prefix gmp`/lib pip install fastecdsa
```

Just wanted to share the findings.

**Comment by Mirko-von-Leipzig** [comment]
Thanks that's good to know!
