### ISSUE TITLE
Verify hashes using common transaction hashing

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1723]
Run the transaction hash verification tool on all networks using #1720.

Also investigate the following

#### Deploy transactions

These deprecated transactions have a version field, but its unknown just how many different versions were actually used.

Its likely that version was only ever one or two but it would be good to confirm. 

It would also be beneficial to know what versions are present on mainnet specifically. Since goerli is deprecating, we can restrict the version numbers to whatever is currently on mainnet. Although this does run the risk of invalidating ancient custom networks. Food for thought - I'm not aware of any custom networks that old though.

#### Deploy account transactions

Check if there are any version zero transactions in any network. Currently we allow any version in the V0V1 handling of this, and we only have a V1 example.

#### L1 Handler transactions

Apparently these [are all version zero](https://github.com/starkware-libs/starknet-specs/pull/190); ~would be good to confirm this.~ confirmed in the PR thread, no work required.

**Comment by kkovaacs** [comment]
> Run the transaction hash verification tool on all networks using #1720.
> 
> Also investigate the following
> 
> #### Deploy transactions
> These deprecated transactions have a version field, but its unknown just how many different versions were actually used.
> 
> Its likely that version was only ever one or two but it would be good to confirm.
> 
> It would also be beneficial to know what versions are present on mainnet specifically. Since goerli is deprecating, we can restrict the version numbers to whatever is currently on mainnet. Although this does run the risk of invalidating ancient custom networks. Food for thought - I'm not aware of any custom networks that old though.

Mainnet has Deploy transactions with transaction version zero and one:
- Zero: https://starkscan.co/tx/0x00e0a2e45a80bb827967e096bcf58874f6c01c191e0a0530624cba66a508ae75
- One: https://starkscan.co/tx/0x01caa872e1d6e75958df2b3d86f5553db7351f68cabb522899f12e4ca1b7890b

These two are the only possible versions for deploy.

> #### Deploy account transactions
> Check if there are any version zero transactions in any network. Currently we allow any version in the V0V1 handling of this, and we only have a V1 example.

This has already been fixed since in the code. The only valid versions are 1 and 3.

**Comment by Mirko-von-Leipzig** [comment]
> Mainnet has Deploy transactions with transaction version zero and one:
>
>    Zero: https://starkscan.co/tx/0x00e0a2e45a80bb827967e096bcf58874f6c01c191e0a0530624cba66a508ae75
>    One: https://starkscan.co/tx/0x01caa872e1d6e75958df2b3d86f5553db7351f68cabb522899f12e4ca1b7890b
>
> These two are the only possible versions for deploy.

Sounds like this is the only remaining "ambiguity" then. Follow up issue to split the `Deploy` variant into two specific variants for v0 and v1 then?

**Comment by Mirko-von-Leipzig** [comment]
Thinking about it; would actually be a good time to change the deploy variants for storage. We can combine it with my V1 storage fix.

**Comment by kkovaacs** [comment]
Yeah, that's a good idea I think.

**Comment by kkovaacs** [comment]
I've also ran `verify_transaction_hashes` for both mainnet and Sepolia testnet and transaction hashes are matching.

**Comment by kkovaacs** [comment]
> Thinking about it; would actually be a good time to change the deploy variants for storage. We can combine it with my V1 storage fix.

Now that fix is on `main` -- do we still want to modify the V1 storage variant? Since it's probably only me having an incompatible database anyway I think we still should do that.

**Comment by Mirko-von-Leipzig** [comment]
> > Thinking about it; would actually be a good time to change the deploy variants for storage. We can combine it with my V1 storage fix.
> 
> Now that fix is on `main` -- do we still want to modify the V1 storage variant? Since it's probably only me having an incompatible database anyway I think we still should do that.

Yes I think let's just do it.
