### ISSUE TITLE
websocket issue / pathfinder v0.11.0-rc0

### ISSUE THREAD

**Issue by tardigralice** [eqlabs/pathfinder#1765]
i am using pathfinder v0.11.0-rc0

 i have added --rpc.websocket.enabled on my pathfinder start command, but i can't send requests (i presumed ws port is http+1, so 9546)

```
wscat -c ws://127.0.0.1:9546 -x '{"jsonrpc":"2.0","id":"0","method":"starknet_getBlockWithTxs","params":["pending"]}'
connect ECONNREFUSED 127.0.0.1:9546
```

**Comment by kkovaacs** [comment]
WebSocket should be available on the _same_ port under the `/ws` path.

**Comment by Mirko-von-Leipzig** [comment]
Feel free to re-open if this didn't resolve your problem.
