### ISSUE TITLE
Review gateway types post v0.13.2

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1777]
Starknet v0.13.0, v0.13.1 and v0.13.2 introduced several new block header fields, which we've made optional in our DTOs in order to support the version transitions.

Once all networks have deployed v0.13.2 we should review these fields and drop the optional if the fields are also present in the historical block data. i.e. if the new fields are also present for genesis block then we don't need the optional.

**Comment by kkovaacs** [comment]
For reference: [Starknet 0.13.2 release notes](https://docs.starknet.io/starknet-versions/version-notes/#version0.13.2)

**Comment by kkovaacs** [comment]
It looks like all fields that have been added in 0.13.2 are present _only_ for 0.13.2+ blocks:

- For block headers: `receipt_commitment`, `state_diff_commitment` and `state_diff_length`.
- For transaction receipts: `total_gas_consumed` and new builtin counters.

This means that we can't really make these fields required, as that would break deserialization of older blocks (even as received from the 0.13.2+ feeder gateway).
