### ISSUE TITLE
Requirements Failures

### ISSUE THREAD

**Issue by kschroed** [eqlabs/pathfinder#181]
Running latest "Ubuntu 18.04.6 LTS" trying to install requirements via: PIP_REQUIRE_VIRTUALENV=true pip install -r requirements-dev.txt

Received many failures where the referenced version is not available.

ERROR: Could not find a version that satisfies the requirement cachetools==5.0.0 (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1, 4.0.0, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4)
ERROR: No matching distribution found for cachetools==5.0.0

ERROR: Could not find a version that satisfies the requirement frozenlist==1.3.0 (from versions: 1.0.0a0, 1.0.0, 1.1.0, 1.1.1, 1.2.0a8, 1.2.0)
ERROR: No matching distribution found for frozenlist==1.3.0

ERROR: Could not find a version that satisfies the requirement multidict==6.0.2 (from versions: 1.0.0a0, 1.0.14, 1.1.0b5, 1.1.0b6, 1.1.0b7, 1.1.0b8, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2 3.1.3a0, 3.1.3, 3.1.4a0, 3.1.4a1, 3.1.4a2, 3.1.4a3, 3.2.0a3, 3.2.0, 3.2.1a0, 3.3.0, 3.3.1, 3.3.2, 4.0.0, 4.1., 4.4.0a2, 4.4.0a3, 4.4.0a4, 4.4.0a5, 4.4.0a6, 4.4.0a7, 4.4.0a8, 4.4.0a9, 4.4.0a10, 4.4.0a11, 4.4.0a12, 4.4.0a17, 4.4.0a18, 4.4.0a19, 4.4.0a20, 4.4.0a21, 4.4.0a22, 4.4.0a23, 4.4.0a24, 4.4.0a25, 4.4.0a26, 4.4.0a27, 4.4.0a32, 4.4.0a33, 4.4.0a34, 4.4.0a35, 4.4.0a36, 4.4.0a37, 4.4.0a38, 4.4.0a39, 4.4.0a40, 4.4.0a42, 4.4.0, 4.4.1, 4.a3, 4.6.0, 4.6.1, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 5.0.0, 5.0.1, 5.0.2, 5.1.0, 5.2.0a0, 5.2.0a5, 5.2.0)
ERROR: No matching distribution found for multidict==6.0.2

ERROR: Could not find a version that satisfies the requirement numpy==1.22.2 (from versions: 1.3.0, 1.4.1, 1.5.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6,.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0,
ERROR: No matching distribution found for numpy==1.22.2

ERROR: Could not find a version that satisfies the requirement platformdirs==2.5.0 (from versions: 2.0.0a1, 2.0.0a2, 2.0.0a3, 2.0.0, 2.0.2, 2.1.0, 2.2.0, 2.3.0, 2.4.0)
ERROR: No matching distribution found for platformdirs==2.5.0

ERROR: Could not find a version that satisfies the requirement pyrsistent==0.18.1 (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 0.11.11, 0.11.12, 0.11.13, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.14.7, 0.14.8, 0.14.9, 0.14.10, 0.14.11, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.15.7, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4rc1, 0.18.0)
ERROR: No matching distribution found for pyrsistent==0.18.1

ERROR: Could not find a version that satisfies the requirement pytest-asyncio==0.18.1 (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.2.0, 0.3.0, 0.4.1, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.10.0.dev0, 0.10.0, 0.11.0, 0.12.0, 0.14.0, 0.15.0, 0.15.1, 0.16.0)
ERROR: No matching distribution found for pytest-asyncio==0.18.1

**Comment by kschroed** [comment]
Attempted remediating requirements.txt to use the latest available but pytest fails after I got through requirements install.

(.venv) root@mn-01:/opt/pathfinder/py# pytest
============================================================================== test session starts ==============================================================================
platform linux2 -- Python 2.7.17, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /opt/pathfinder/py, inifile: setup.cfg
collected 0 items / 3 errors

==================================================================================== ERRORS =====================================================================================
_______________________________________________________________________ ERROR collecting src/test_call.py _______________________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/opt/pathfinder/py/src/test_call.py", line 238
E       f'{{ "at_block": 1, "contract_address": {contract_address}, "entry_point_selector": "get_value", "calldata": [132] }}',
E                                                                                                                            ^
E   SyntaxError: invalid syntax
____________________________________________________________ ERROR collecting src/test_generate_test_global_tree.py _____________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
src/test_generate_test_global_tree.py:1: in <module>
    from generate_test_global_tree import generate_root_and_nodes, parse_value, parse_bytes
E     File "/opt/pathfinder/py/src/generate_test_global_tree.py", line 25
E       async def generate_root_and_nodes(input):
E               ^
E   SyntaxError: invalid syntax
____________________________________________________________ ERROR collecting src/test_generate_test_storage_tree.py ____________________________________________________________
/usr/lib/python2.7/dist-packages/_pytest/python.py:403: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python2.7/dist-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
/usr/lib/python2.7/dist-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
src/test_generate_test_storage_tree.py:1: in <module>
    from generate_test_storage_tree import generate_root_and_nodes, parse_value
E     File "/opt/pathfinder/py/src/generate_test_storage_tree.py", line 19
E       async def generate_root_and_nodes(input):
E               ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 3 error in 0.25 seconds ============================================================================

**Comment by aphelionz** [comment]
Looks like you're running Python 3.6. Please try 3.8 or higher and let us know if that works better.

**Comment by kschroed** [comment]
Ok yeah that is getting me further now. May want to update the instructions. It is unclear that 3.8 is the minimum requirement. Just mentions your version may very.

**Comment by kschroed** [comment]
Also to note 3.8 is not directly available with native 18.04 LTS so had to add different apt repos etc in order to make it work and update-alternatives to point at specific version.

**Comment by Mirko-von-Leipzig** [comment]
The readme does mention requiring 3.7 or up but I agree its not very prominent -- and isn't mentioned again during the python section so it could use work :)

Unfortunately this python version requirement is not in our control at all.

**Comment by Mirko-von-Leipzig** [comment]
Updated instructions a bit in #185
