### ISSUE TITLE
Change Docker path to /var/lib/pathfinder or similar

### ISSUE THREAD

**Issue by aphelionz** [eqlabs/pathfinder#189]
Hmm, shouldn't this be something like `/var/lib/pathfinder`?

According to the [Linux Filesystem Hierarchy Standard](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html):

> The /usr/share hierarchy is for all read-only architecture independent data files. [[30]](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html#ftn.idm236091847456)

And for `/var/lib` ([FHS reference](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s08.html)):

> This hierarchy holds state information pertaining to an application or the system. State information is data that programs modify while they run, and that pertains to one specific host. Users must never need to modify files in /var/lib to configure a package's operation, and the specific file hierarchy used to store the data must not be exposed to regular users.

_Originally posted by @kkovaacs in https://github.com/eqlabs/pathfinder/pull/168#discussion_r823416757_

**Comment by koivunej** [comment]
Sadly changing it now that we have docker image users requires everyone to reconfigure everything. I don't know how valid this issue is anymore that we have `--data-directory` which can be used to override the default current working directory.

**Comment by aphelionz** [comment]
Agree, `--data-directory` handles this sufficiently.
