### ISSUE TITLE
/health API endpoint needed

### ISSUE THREAD

**Issue by aphelionz** [eqlabs/pathfinder#194]
When running this in a cloud or containerized context, it's necessary to have an endpoint that returns 200 if the pathfinder node is healthy. We can define healthy however we like but I'd say anything in syncing / synced mode would count.

**Comment by aphelionz** [comment]
Alternatively, you could have the root path `/` just return a 200 with an empty body

**Comment by tarrencev** [comment]
+1 would love to support this for my k8s deployment

**Comment by CHr15F0x** [comment]
Related: #261 .

**Comment by fracek** [comment]
I think the service should have a liveness endpoint (`/livez`) and a readyness one (`/readyz`). I like how the k8s [api](https://kubernetes.io/docs/reference/using-api/health-checks/) not only returns a success response but also some extra information to debug what went wrong.

**Comment by tarrencev** [comment]
Unfortunately it seems even with the newer `jsonrpsee` it is not possible to register handlers outside of their abstraction. Would pathfinder be open to adding an additional listener to expose this? Or should we try work with jsonrpsee to expose the necessary functionality?

**Comment by tarrencev** [comment]
Registering a health handler is now supported upstream: https://github.com/paritytech/jsonrpsee/pull/763

**Comment by fracek** [comment]
I will start working on this in the upcoming weeks. The health probes and metrics endpoints should be on a separate port anyway so I don't think we need to change the rpc code too much. The plan is to start a warp server that serves the right routes.

**Comment by Mirko-von-Leipzig** [comment]
Added in #513.

**Comment by aphelionz** [comment]
Thanks @Mirko-von-Leipzig !
