### ISSUE TITLE
Pending block incorrectly has `status` field in all version of the RPC

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1974]

**Comment by kkovaacs** [comment]
Which RPC versions do we want to fix this for?

I'd be reluctant to change old JSON-RPC versions (like 0.4 and 0.5).

**Comment by Mirko-von-Leipzig** [comment]
> Which RPC versions do we want to fix this for?
> 
> I'd be reluctant to change old JSON-RPC versions (like 0.4 and 0.5).

I'm happy to only do this for v0.7, and v0.6 if its simple enough.

**Comment by kkovaacs** [comment]
> > Which RPC versions do we want to fix this for?
> > I'd be reluctant to change old JSON-RPC versions (like 0.4 and 0.5).
> 
> I'm happy to only do this for v0.7, and v0.6 if its simple enough.

Fixing this would mean adding a "pending block" DTO for v0.6 though -- that's currently missing.

> One alternative approach is to implement all the DTOs for v0.7 - but that's a lot more work than just fixing the bug I think.

Yep, that's quite a bit more involved, especially as it involves transaction DTOs.

**Comment by Mirko-von-Leipzig** [comment]
> > > Which RPC versions do we want to fix this for?
> > > I'd be reluctant to change old JSON-RPC versions (like 0.4 and 0.5).
> > 
> > 
> > I'm happy to only do this for v0.7, and v0.6 if its simple enough.
> 
> Fixing this would mean adding a "pending block" DTO for v0.6 though -- that's currently missing.
> 
> > One alternative approach is to implement all the DTOs for v0.7 - but that's a lot more work than just fixing the bug I think.
> 
> Yep, that's quite a bit more involved, especially as it involves transaction DTOs.

Then let's just fix v0.7. Since its only been reported the once after so long :)
