### ISSUE TITLE
Bug: Docker image won't run on ARM64 systems with non 4KB page size

### ISSUE THREAD

**Issue by xJonathanLEI** [eqlabs/pathfinder#1982]
This is because the default build option in `jemalloc` uses the host page size, even when cross-compiling. See https://github.com/jemalloc/jemalloc/issues/467#issuecomment-2054282344 for details.

The `--with-lg-page` option must be set to fix this.

```log
pathfinder@node-1:/usr/share/pathfinder/data$ pathfinder
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
Aborted (core dumped)
```

This affects lots of ARM64 devices like Macs with Apple Silicon and Raspberry Pi 5 running Raspberry Pi OS (Ubuntu on RPI 5 uses 4KB page size so it still works).

**Comment by kkovaacs** [comment]
@xJonathanLEI I've built a Docker image for testing that _should_ be OK for non-4K page sizes on ARM64. Unfortunately I can't test that image myself (no access to a non-4K pagesize AMR64 system). Would you mind checking if [this snapshot image](https://hub.docker.com/layers/eqlabs/pathfinder/snapshot-a87e82cb1d660d01e28456dcea2fe86abb412cb4/images/sha256-14432bdb4fae888524b2d737b0bb5f3905a1880f2b2c2d153580d6eb2874a897) works for you?

**Comment by xJonathanLEI** [comment]
@kkovaacs Yep works perfectly on my RPI 5 running 16KB kernel:

<img width="950" alt="image" src="https://github.com/eqlabs/pathfinder/assets/19556359/cf0d6f19-80be-41d1-ad11-d512ae176f2f">

**Comment by xJonathanLEI** [comment]
Did you build this with `--with-lg-page 16`?

**Comment by kkovaacs** [comment]
> Did you build this with `--with-lg-page 16`?

Yes, so it should work with 64K pages too.

**Comment by xJonathanLEI** [comment]
Some additional notes on performance: https://github.com/dojoengine/dojo/issues/1913#issuecomment-2092439764.
