### ISSUE TITLE
Enable additional clippies

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#1997]
We currently use the default clippy settings. 

I suggest we enable some additional ones. Peruse the `allowed` clippies and consider adding some, some suggestions

- [cargo manifest group](https://rust-lang.github.io/rust-clippy/master/index.html#?groups=cargo)
- [missing safety docs](https://rust-lang.github.io/rust-clippy/master/index.html#/undocumented_unsafe_blocks)

To see other potential positives can run with all clippies enable to see what jumps out.

**Comment by kkovaacs** [comment]
I've given the `cargo` group a try -- none of those lints seems useful:

- missing metadata in our (internal) crates we do not intend to publish to crates.io
- multiple versions of the same dependencies -- mostly transitive dependencies we cannot do much about.

**Comment by Mirko-von-Leipzig** [comment]
Another idea I've had is to enforce auditing of potential causes of panic. Ideally (imo) e.g.`unwrap`, raw slice indexing `x[i]` in prod code should all come with a `SAFETY` style comment.

`clippy` only has a lint for this for `unsafe` blocks directly. But one can achieve the same thing by doing:

1. Set the relevant clippy lint(s) to warning e.g. [slicing](https://rust-lang.github.io/rust-clippy/master/index.html#indexing_slicing). Warning should be upgraded to deny in CI. Code no longer compiles.
2. Insert a `#[allow(<lint>, reason = "unaudited")]` about each offense. Code now compiles again as before.
3. Begin manually auditing and filling in proper reasons, or refactoring to avoid it.
