### ISSUE TITLE
Support configuration via environment variables

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#201]
Environment variables are the de-facto standard for deployment configuration. This would be a third configuration method since we already have cmd line args and toml file.

I would suggest that env vars have the lowest priority i.e. the other methods override them. The env vars should also be namespaced i.e. have a `PATHFINDER_` prefix (unless this is against some standard? I'm not too knowledgeable here).

We should consider using a config management library before this gets out of hand :)

Some minimal prior discussion [here](https://github.com/eqlabs/pathfinder/pull/200#discussion_r826277262).

**Comment by CHr15F0x** [comment]
Fixed in #221 .
