### ISSUE TITLE
Docker buildx failure: rust:1.59-alpine: no match for platform in manifest 

### ISSUE THREAD

**Issue by aphelionz** [eqlabs/pathfinder#210]
https://github.com/eqlabs/pathfinder/actions/runs/2016262256

> buildx failed with: error: failed to solve: rust:1.59-alpine: no match for platform in manifest sha256:beec2294d9aa990c6b0c7eda2026af476128ee255e44bcd7a2f8b67859fb738a: not found

@odyslam are you available to help debug this?

**Comment by odyslam** [comment]
@aphelionz Yup. The alpine flavor doesn't come in arm32v7. In my builds, I used Debian, as I don't care about the size of the builder since I simply copy the binary to the runner (which is an alpine).

That architecture is used by raspberrypi3 and zero, as also other boards such as the beaglebone.

**Comment by aphelionz** [comment]
Can we remove it for now just to get the build running? I'd rather not move away from Alpine at this moment.

**Comment by odyslam** [comment]
@aphelionz out of curiosity, what change would the Debian bring? Given the multi-stage build, I would imagine that the end image size would be unchanged.

Am I missing something (genuine question)?

Also, note that without a raspberry pi 3/zero support, we can't have 5-minute. 1-click deployment for these platforms. 

Currently, it takes about 40 minutes for the docker to be built with every deployment (versus just downloading the image).

**Comment by odyslam** [comment]
Right, thanks for the insight!

I have a feeling that since we removed the --target, it should build with the default linker which is libc?

**Comment by koivunej** [comment]
I think this can be closed since in #324 we switched to using bullseye images, but of course we still don't have anything arm7.
