### ISSUE TITLE
Add block number to `starknet_syncing` method

### ISSUE THREAD

**Issue by NikitosnikN** [eqlabs/pathfinder#226]
I, as a developer, want to know that is headlag (`highest_block` - `current_block`) of my running node to build properly monitoring in Grafana.

In current implementation `starknet_syncing` method returns hashes of blocks. Example:
```
{
  "jsonrpc": "2.0",
  "result": {
    "starting_block": "0x3f6a2d3764762221eb98036a4b2e88fd30a5430ce8f3b148e4867deafcdf9a8",
    "current_block": "0x76e4a1afe7e0e83047b08f8b0ee3f4d05908f9195ab11a4a15b4c156dd74ed2",
    "highest_block": "0x6b9abe86c83a64fb608ef2deb87045eae7a062cdc69410e1ea1cfb663285dc4"
  },
  "id": 0
}
```

I'm able to get `current_block` number from `starknet_blockNumber` method, but I'm unable to get `highest_block` block number because node is not fully synced yet, and it is not aware of `highest_block`

The main reference for this implementation is geth `eth_syncing` method, which returns the same structure, but instead of hashes it returns block numbers in hexadecimals 

```
{
    "jsonrpc": "2.0",
    "id": 64,
    "result": {
        "startingBlock": "0x20e76cc",
        "currentBlock": "0x20e76df",
        "highestBlock": "0x20e76e0"
    }
}
```

**Comment by CHr15F0x** [comment]
Fixed in #265 as per the [updated spec](https://github.com/starkware-libs/starknet-specs/blob/79ce68d55f4c5bc4796305bf8ed9b5b2f432653e/api/starknet_api_openrpc.json#L717).
