### ISSUE TITLE
Inconsistencies with getProof endpoint

### ISSUE THREAD

**Issue by petscheit** [eqlabs/pathfinder#2260]
I am currently implementing a verification script for storage proofs queries via `pathfinder_getProof`. In the process I have run into some inconsistencies.

### Issue 1 - Invalid Edge Node:
For testing, I have declared and deployed the following contract to sepolia: [0x06b8838af5d2a023b24ec8a69720b152d72ae2e4528139c32e05d8a3b9d7d4e7](https://sepolia.voyager.online/tx/0x04d111e27ba10758859caf457f4a8049ccb1983f50c70673ae14385151ee19bb)

```
#[starknet::contract]
mod TestContract {
    use starknet::ContractAddress;

    #[storage]
    struct Storage {
        supply: u256,
    }

    #[constructor]
    fn constructor(ref self: ContractState, initial_supply: u256) {
        self.supply.write(initial_supply);
    }
}
```

To generate the proof for the supply variable, I do `sn_keccak("supply") -> 0x0308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850a`. I have confirmed this key is correct via voyager.

To fetch the proof, I set the following params:

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "pathfinder_getProof",
    "params": [
        {"block_number": 202485},
        "0x06b8838af5d2a023b24ec8a69720b152d72ae2e4528139c32e05d8a3b9d7d4e7",
        [
            "0x0308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850a"
        ]
    ]
}
```

While the contract proof looks correct, the contract data proof doesn't seem to make any sense. 

(ignoring some sections of the response)
```
"contract_data": {
    "class_hash": "0x1db2b3692c1fe6e3a50e8e9d19f57d6f2649ac4c4663a1e744976d495f20f6a",
    "contract_state_hash_version": "0x0",
    "nonce": "0x0",
    "root": "0x38c1afc6f0ba338b16cd0224e5d0cd5bcacd9744a5fad9c7cd55164a3f60fc6",
    "storage_proofs": [
        [
            {
                "edge": {
                    "child": "0x5e8e21587583b06417997f8a8c167ac84a59a88ba0361928704e8554b2b9e0a",
                    "path": {
                        "len": 250,
                        "value": "0x18467ddbe969c6d9d10afcb94280d634a22d357df719466f572711edaa5c285"
                    }
                }
            },
            {
                "binary": {
                    "left": "0xa1b01d4b1c7",
                    "right": "0x20566c4238e"
                }
            }
        ]
    ]
},
```
Two things stand out here immediately:
1. The value of the edge node is wrong (should be `0x0a1b01d4b1c7`, can be confirmed via tx calldata and voyager read state)
2. The path of the edge node does not match the storage address at all

### Issue 2 - Incorrect mpt proof for storage address:
I have also generated storage proofs for [STRK balance on mainnet](https://voyager.online/contract/0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d). Since the [Starkgate contract ](https://github.com/starknet-io/starkgate-contracts/blob/cairo-1/src/cairo/strk/erc20_lockable.cairo) represents the balance as `uint256` I need to generate a proof for both storage addresses (low + high).

The STRK contract is deployed as: 

I generate the storage addresses with:

```
addrs_low = pedersen(sn_keccak("ERC20_balances"), 0x02046b54093e5b8d98397869927df141136a4d6c761169967176a0681d35be1b); # => 0x3b92238d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ed
addrs_high = addrs_low + 1
```
Again, I have verified the correctness of these keys via voyager.

To generate the proof I set the following params:

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "pathfinder_getProof",
    "params": [
        {"block_number": 726485},
        "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
        [
            "0x3b92238d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ed",
            "0x3b92238d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ee"
        ]
    ]
}
```

The contract state proof for the first storage address is valid, and I am able to confirm it without issues. Weird however, is the proof that is generated for the second storage address. For some reason, the second proof points to the same edge node as the first one.

```
 "contract_data": {
      "class_hash": "0x4ad3c1dc8413453db314497945b6903e1c766495a1e60492d44da9c2a986e4b",
      "contract_state_hash_version": "0x0",
      "nonce": "0x0",
      "root": "0x64a27298e9bf343a29f234897a6e90815c8f7c4a6fc6d3872ae728a1ae2a203",
      "storage_proofs": [
          [
              <binary nodes...>,
              {
                  "edge": {
                      "child": "0x43c33c1937564800000",
                      "path": {
                          "len": 231,
                          "value": "0x38d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ed"
                      }
                  }
              }
          ],
          [
             <binary nodes...>,
              {
                  "edge": {
                      "child": "0x43c33c1937564800000",
                      "path": {
                          "len": 231,
                          "value": "0x38d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ed"
                      }
                  }
              }
          ]
      ]
  }
}
```

As shown above, I receive the proof for the first storage address twice, and no proof for the second address. I have also tried only requesting the proof for the second address. It results in the same situation, I receive the former address proof. 

I have confirmed that the keys are correct,  if I query the second address on voyager, it correctly returns `0x0`

I am very confused by these errors, and would appreciate some help. Appologies for the length of the issue, but I wanted to make sure its clear and reproducible.

**Comment by kkovaacs** [comment]
Let me address the issues one-by-one, this comment tries to answer **issue 1 - invalid edge node**.

You're analysis regarding the storage address & the rest is of course correct, so the getProof arguments are correct as well. Please note that `supply` is an `u256` that is stored as two felts in storage (at keys `0x308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850a` and `0x308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850b`). You're requesting a proof for the first one (the one ending in `a`). Those two keys are the _only_ keys set in storage, so the Merkle Patricia tree for the contract looks like this:

![image](https://github.com/user-attachments/assets/29740650-8257-4b23-b53f-de2b7a458b19)

The path in the edge node seems correct in the response: it's the first 250 bits of the 251 bit key you're requesting (2 * 0x18467ddbe969c6d9d10afcb94280d634a22d357df719466f572711edaa5c285 = 0x0308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850a). The binary node then adds one more 0/1 bit for the left/right leaf values which correctly gives the paths 0x0308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850a and 0x0308cfbb7d2d38db3a215f9728501ac69445a6afbee328cdeae4e23db54b850b as expected.

The values of the binary node's leaves seem to be correct as well ("hashes" for leaf nodes are the values themselves).

**Comment by kkovaacs** [comment]
And this one for **issue 2 - incorrect mpt proof for storage address**:

The addresses again seem correct so the getProof parameters are once again perfect.

The balance for you account seems to be representable on 128 bits, so the storage value at key `0x3b92238d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ed` is zero. That means that key does _not_ exist in the Merkle Patricia tree, so you're getting a non-existence proof for that key.

A non-existence proof is the path to the first node that is non-matching -- in your case it's the edge node leading to the leaf at key `0x38d3ae057fa455c2e182a43661b99f45f4499473d977ec1009a9e805ed`, since that node is the first one whose (aggregate) path does not match the key you've requested.

**Comment by petscheit** [comment]
Thanks for the quick reply! I think I now understand the trie properly. 

Issue 1:
Verified this manually, and everything makes sense now. I was not aware binary nodes could also contain the leaf values. 

Issue 2:
I think I understand. So this is what the trie looks like for inclusion vs non-inclusion for the the leaf having a path ending with `0x1c2d` right? And since we validate the inclusion of a node that passes the path of the non-inclusion node (`0x1c2d` in the diagram), we prove non-inclusion of the other node.

![image](https://github.com/user-attachments/assets/59ba49f0-1150-44e9-b6f7-01a027c6c4f0)

Thanks again, I think I now have a proper picture of the trie, not even sure how my mental model made sense before

**Comment by petscheit** [comment]
Sorry to reopen, but ran into another proof that doesnt make sense to me.

For mainnet, I send this request. The key is a random hash here.
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "pathfinder_getProof",
    "params": [
        {"block_number": 726485},
        "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d",
        [
            "0x4a67b4552e790f10bb91236771c1130dbb33215987328ec900283112afdce0f"
        ]
    ]
}
```

The last node of the contract state proof is now this:

```
{
    "edge": {
        "child": "0x20514dcdf1c42c3af0e71cede999554ce9f6fb60d792e185de186c3400f627b",
        "path": {
            "len": 3,
            "value": "0x3"
        }
    }
}
```

How come the path length of the edge node is 3, when the path is 3? Shouldn't that be 2?
