### ISSUE TITLE
How to config database snapshots  in docker ?

### ISSUE THREAD

**Issue by nocb** [eqlabs/pathfinder#2305]
I have downloaded the zst file and placed it in the directory  pathfinder.
my command is:
`zstd -T0 -d mainnet_0.14.0_751397_pruned.sqlite.zst -o mainnet.sqlite`

```
sudo docker run \
  --name pathfinder \
  --restart unless-stopped \
  --detach \
  -p 9545:9545 \
  --user "$(id -u):$(id -g)" \
  -e RUST_LOG=info \
  -e PATHFINDER_ETHEREUM_API_URL="http://192.168.31.16:19551" \
  -v $HOME/pathfinder:/usr/share/pathfinder/data \
  eqlabs/pathfinder
```

mainnet.sqlite is under the directory  $HOME/pathfinder

my docker log is :
```
2024-10-15 23:31:57 2024-10-15T15:31:57  INFO 🏁 Starting node. version="v0.14.4"
2024-10-15 23:31:53 Error: Setting journal mode to rollback
2024-10-15 23:31:53 
2024-10-15 23:31:53 Caused by:
2024-10-15 23:31:53     0: database disk image is malformed
2024-10-15 23:31:53     1: Error code 11: The database disk image is malformed
2024-10-15 23:31:55 Error: Setting journal mode to rollback
```

thanks

**Comment by kkovaacs** [comment]
Have you checked that the `mainnet_0.14.0_751397_pruned.sqlite.zst` file you have has a matching SHA2-256 checksum? (Should be `2f9aa8b98086c12a1ce14e89ddfe02ebf320a7ba47e63829056a405866568113`.)

If that _does_ match, please check that the SHA2-256 checksum of the _uncompressed_ `mainnet.sqlite` file matches the following: `d4d155d97721dc00a5998c92b8f8492c102157ead3ced68090f1ba2cbd20cfc1`.

**Comment by kkovaacs** [comment]
@nocb Did you have a chance to try the suggestions above?
