### ISSUE TITLE
JSON-RPC 0.8.0: add `CALL_ON_PENDING` error

### ISSUE THREAD

**Issue by kkovaacs** [eqlabs/pathfinder#2378]
Subscription methods not supporting subscribing to pending should return the new CALL_ON_PENDING error.

For reference check [this commit](https://github.com/starkware-libs/starknet-specs/commit/84b9365f502c3717c76864bc3dfbb281f49f9aad) in the specification.

**Comment by t00ts** [comment]
Solved on #2383
