### ISSUE TITLE
Compilation failing on raspberry 3 model B .

### ISSUE THREAD

**Issue by harsh-98** [eqlabs/pathfinder#254]
I have ubuntu server installed on armv7 architecture based raspberry 3. I installed openssl, pkg-config and other pre-requisite. But the compilation is still failing.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/23700929/164431303-37be2c63-b1bb-40e2-a37f-2c382906d852.png">

**Comment by Mirko-von-Leipzig** [comment]
Thanks for reporting this. We're looking into ways to solve this.

**Comment by koivunej** [comment]
So far we've looked into this:
- `bitvec` or bitvec's deps don't currently support BitSlice for align=4 which is less than size of u64, so there's going to be a problem with those (like seen on screenshot)
    - some of bitvec repositories have an issue on this, and proposed solution (align=8 IIRC)
    - linking it here not a priority, we are still stuck on bitvec 0.20 for selected by other deps
- `ff` only supports bignums with `[u64; _]` so those would have to be worked around/generified in the derive

Rest of the issues are currently hidden. It is unlikely we have time for these, but let's keep the issue open to collect other known issues.

**Comment by sergey-melnychuk** [comment]
Closing the issue for now. Please feel free to reopen if the issue is still relevant.
