### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by asokol1981** [eqlabs/pathfinder#271]
Hi!
I have pathfinder installed in unprivileged lxc container and it working, but today at 00:22:48 UTC syslog received this error first time. Now syslog contains only two constantly repeating entries:
```
L1 sync process restarted.
L1 sync process terminated with: Error getting logs: Transport("response status code is not success: 429 Too Many Requests")
```
What can be done to fix this error?

**Comment by Mirko-von-Leipzig** [comment]
This is a result of our pathfinder node sending too many queries to your L1 node service and it is rate limiting pathfinder. We are working on reducing the amount of queries we send.

Pathfinder will continue to work as is; it will keep retrying the L1 endpoint until the rate limiting ends. L1 services usually have a set limit of daily queries, so you'll likely see the error -> restart repeat until the end of a day. And then start at some point the next day, where we have exceeded the limit again.

**Comment by asokol1981** [comment]
Thank you for response! Take care. :)
