### ISSUE TITLE
Implement Pedersen hash

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#33]
This is the major hash function used by StarkNet. Will be required to calculate contract hashes as well as Merkle Patricia Trees.

[Starkware basic docs](https://docs.starkware.co/starkex-v3/crypto/pedersen-hash-function), which contains links to some implementations.

[This Starkware python implementation](https://github.com/starkware-libs/starkex-resources/blob/master/crypto/starkware/crypto/signature/fast_pedersen_hash.py) seems easier to understand. It uses [fastecdsa python library](https://github.com/AntonKueltz/fastecdsa) to perform the elliptical curve maths.

A possible starting point is the [elliptic_curve](https://docs.rs/elliptic-curve/0.10.6/elliptic_curve/) rust library. This is hopefully equivalent to the `fastecdsa` python library used by starkware's impl.

**Comment by koivunej** [comment]
Impl'd in #45, probably good enough to close for now.
