### ISSUE TITLE
RPC method "starknet_getEvents" option "address" filters on sender

### ISSUE THREAD

**Issue by Neozaru** [eqlabs/pathfinder#331]
Environment:
- Starknet Goerli

It looks like the `address` filter for `starknet_getEvents` method filters on the EOA address from which the tx is originating.
If the goal is to have a similar behavior as https://www.quicknode.com/docs/ethereum/eth_getLogs, shouldn't `address` be used to filter on from which contract the event log is originating ?
The workaround on my side will probably be to add the contract address as one of the arguments of the event, so I can fetch all events with the topic/key I am looking for, then select only the ones originating from the contract I am targeting.
However this means that if other users deploy smart-contract with the same event key, I'll have to pull their logs, which will make requests bigger.

Unsure if this is just working by design or not, but I would suggest enabling the possibility of adding a "contract" filter to `starknet_getEvents`.
I am open to suggestions or to learn more about it if this is a limitation due to technical concerns.

**Comment by Mirko-von-Leipzig** [comment]
As I understand, a StarkNet event has two associated addresses.

1. The event transaction's contract address
2. The event's `from_address`

(1) is the one filtered against using `address`. (2) is available as part of each returned `Event`. Are you wanting to pre-filter by (2)?

**Comment by Neozaru** [comment]
Thanks for your response.

Ideal feature: Detect specific events emitted by a specific contract so I can track actions performed through this contract, regardless of who initiated those actions.
Ideal query filter: By contract address + by event type(s)
Ideal output: Events with event type, event arguments, original tx caller

In my case:
- Contract address is: 0x042ef2d59592aaa267ab4aae511e82de7c994fc0c7a3e01762a54d3090598d52
- My account is 0x051646efc832a88c0bb5b5b8a353ebd2667c402fba1af8523300d94578a8cb00 (ArgentX)
- The event I want to catch is 64567595156829316170797493317192700520167169075456128699642487511717762122 or 0x248B4135FE123080010C53142C4D13419491D53E468909F80E1D3F429BD44A in hex
- A test tx for this is https://goerli.voyager.online/tx/0x6c2604f0b1cc0732203676654531303438d72485fcfc7e09edb4a19a478ba35#events

The way I try to query the event for the contract is:
(note that I can't add `"address":"0x042ef2d59592aaa267ab4aae511e82de7c994fc0c7a3e01762a54d3090598d52"` to this query as this results in no event.)
```
{"jsonrpc":"2.0","id":"barbaz","method":"starknet_getEvents","params":{"filter":{"page_size":1024,"fromBlock":225939,"toBlock":225939,"page_number":0,"keys":["0x248B4135FE123080010C53142C4D13419491D53E468909F80E1D3F429BD44A"]}}}
```
The output I get:
```
{
        "data": [
          "0x51646efc832a88c0bb5b5b8a353ebd2667c402fba1af8523300d94578a8cb00",
          "0x57ce2a52140f0661aaaa66cb1332fa56f95652d967ceeaf8ff8fd4c63b8745b",
          "0x3d0900",
          "0x0"
        ],
        "keys": [
          "0x248b4135fe123080010c53142c4d13419491d53e468909f80e1d3f429bd44a"
        ],
        "from_address": "0x51646efc832a88c0bb5b5b8a353ebd2667c402fba1af8523300d94578a8cb00",
        "block_hash": "0x11d6d925d410b3cbbce99f1cc728f223b36b91c604321d472dbb05fb67f33e5",
        "block_number": 225939,
        "transaction_hash": "0x6c2604f0b1cc0732203676654531303438d72485fcfc7e09edb4a19a478ba35"
      }
```
For which none of the fields indicates my original contract address 0x042ef2d59592aaa267ab4aae511e82de7c994fc0c7a3e01762a54d3090598d52

However I now have a transaction hash so I can do:
```
{"jsonrpc":"2.0","id":"barbaz","method":"starknet_getTransactionByHash","params":["0x6c2604f0b1cc0732203676654531303438d72485fcfc7e09edb4a19a478ba35"]}
```
which gives me:
```
{
    "txn_hash": "0x6c2604f0b1cc0732203676654531303438d72485fcfc7e09edb4a19a478ba35",
    "contract_address": "0x51646efc832a88c0bb5b5b8a353ebd2667c402fba1af8523300d94578a8cb00",
    "entry_point_selector": "0x15d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad",
    "calldata": [
      "0x1",
      "0x42ef2d59592aaa267ab4aae511e82de7c994fc0c7a3e01762a54d3090598d52", <-- Here my contract address
      "0xc73f681176fc7b3f9693986fd7b14581e8d540519e27400e88b8713932be01",
      "0x0",
      "0x3",
      "0x3",
      "0x57ce2a52140f0661aaaa66cb1332fa56f95652d967ceeaf8ff8fd4c63b8745b",
      "0x3d0900",
      "0x0",
      "0xb"
    ]
  }
```
which now I can see the second argument of the calldata is my contract address, allowing me to safely validate that the event originates from my contract (?).

Ideally what I'd like to have (and seen on `getLogs` Ethereum implementation I believe) is the ability to filter Events by contract who emitted them.
Here the `address` filter of `starknet_getEvents` will respond to my own wallet address only, not to the contract address. This might be due to the fact that ArgentX is a smart-wallet, hence the workflow being [my priv key] -> [my argent smart-contract wallet] -> [my contract] and thus the events are emitted on behalf on my smart-contract wallet.

I am happy to provide more detail. It might also be a misunderstanding from me of the internals of StarkNet.

**Comment by Mirko-von-Leipzig** [comment]
Hmm. Judging from the fact that voyager correctly identifies your contract address as the `from_address` I would wager that this is a bug on our end. Or your last thought on the argent-x flow is correct and voyager has some extra special integration for argent-x addresses.

I'll have a look into this; will likely take at least a day or two since we are dealing with the StarkNet 0.9 update.

Really want to say thanks for the excellent issue write up, info and leg-work you've done.

**Comment by Mirko-von-Leipzig** [comment]
We've identified this as a bug on our end where we are storing the transaction address instead of the event's address. Once fixed, the output for your query:
```
{"jsonrpc":"2.0","id":"barbaz","method":"starknet_getEvents","params":{"filter":{"page_size":1024,"fromBlock":225939,"toBlock":225939,"page_number":0,"keys":["0x248B4135FE123080010C53142C4D13419491D53E468909F80E1D3F429BD44A"]}}}
```
should change the `from_address` to your contract's address.
```
{
        "data": [
          "0x51646efc832a88c0bb5b5b8a353ebd2667c402fba1af8523300d94578a8cb00",
          "0x57ce2a52140f0661aaaa66cb1332fa56f95652d967ceeaf8ff8fd4c63b8745b",
          "0x3d0900",
          "0x0"
        ],
        "keys": [
          "0x248b4135fe123080010c53142c4d13419491d53e468909f80e1d3f429bd44a"
        ],
        "from_address": "0x042ef2d59592aaa267ab4aae511e82de7c994fc0c7a3e01762a54d3090598d52",
        "block_hash": "0x11d6d925d410b3cbbce99f1cc728f223b36b91c604321d472dbb05fb67f33e5",
        "block_number": 225939,
        "transaction_hash": "0x6c2604f0b1cc0732203676654531303438d72485fcfc7e09edb4a19a478ba35"
}
```

Unfortunately this does mean that your database (and everyones) event data is broken in the same way. We are looking into mitigations but its likely that the recourse is to sync from zero again. We are working on a new, non-corrupt snapshot which should at least ease the pain a bit.

**Comment by Neozaru** [comment]
Thanks @Mirko-von-Leipzig that sounds good.
About the `address` filter, will this change make it work similar to `eth_getLogs` (in the sense of inserting the contract address to get events emitted by the contract), or will the change only change the `from_address` in the responses ?

**Comment by Mirko-von-Leipzig** [comment]
> Thanks @Mirko-von-Leipzig that sounds good. About the `address` filter, will this change make it work similar to `eth_getLogs` (in the sense of inserting the contract address to get events emitted by the contract), or will the change only change the `from_address` in the responses ?

The latter only. I'll re-open the issue; apologies.

Just to clarify again, givent that there are two addresses related to an event:

1. the transaction's contract address
2. the event's `from_address`

which of these are these are you expecting to be able to filter by? (1), (2) or both? Ethereum's `getLogs` also supports an array of addresses while the starknet RPC API does not.

**Comment by Mirko-von-Leipzig** [comment]
Thanks again for raising this issue. Would likely have slipped right by us :) I'm closing the issue again, but feel free to re-open if it still doesn't work.

**Comment by Mirko-von-Leipzig** [comment]
@Neozaru good news --  we believe we should be able to salvage the databases. Hopefully our next release `0.2.2-alpha` will include a database migration to fix past events. So no need to resync :) 🤞
