### ISSUE TITLE
Return value of `starknet_getBlockByHash` when block is not found

### ISSUE THREAD

**Issue by fracek** [eqlabs/pathfinder#363]
When I make a call to `starknet_getBlockByHash` with a block hash that doesn't match any existing block I receive back an error response:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": 24,
    "message": "Invalid block hash"
  },
  "id": 1
}
```

What I expect in this case is to receive an empty result:

```json
{
  "jsonrpc": "2.0",
  "result": null,
  "id": 1
}
```

I opened an issue an not a PR because I'm not sure it's a bug in the implementation or in the spec. The second return value is much more useful because it's clear the issue is that the block doesn't exist, while in the first case it's not clear if it's a malformed block hash or a missing block.

**Comment by CHr15F0x** [comment]
I am also unsure what you mean by a missing block. In our implementation we store all blocks up to the local L2 sync head.

**Comment by Mirko-von-Leipzig** [comment]
@CHr15F0x I think the point is that the message is ambiguous.

"Invalid block hash" could mean either (or both):
- a block with that hash does not exist
- the provided block hash is not parseable

Some better wording would be:
- block does not exist
- block hash is malformed

However, unforunately the spec defines the non-existant block error [here](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1295) using the ambiguous wording:
```
"INVALID_BLOCK_HASH": {
    "code": 24,
    "message": "Invalid block hash"
}
```
so we are somewhat stuck with it.

We should probably amend our malformed error message to not mention internal types.

**Comment by Mirko-von-Leipzig** [comment]
Somewhat interestingly, I see the spec defines the [INVALID_CONTRACT_CLASS_HASH](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1311) message with a bit more definition..
```
"message": "The supplied contract class hash is invalid or unknown"
```
which appears to mean that it should include both malformed and missing cases? Which would not be great..

**Comment by CHr15F0x** [comment]
Hmm the message you quoted still does not distinguish between malformed and unknown, so imho this is still the very same case as in for example invalid block hash. I am afraid it would be hard to detect malformed hashes except for some blatant cases.

**Comment by Mirko-von-Leipzig** [comment]
In the context of the message I would assume `invalid` means `malformed` since it mentions `unknown` which would be the hash does not exist in our database.

> I am afraid it would be hard to detect malformed hashes except for some blatant cases.

It would just be any input that is not a `BLOCK_HASH_OR_TAG`?

**Comment by CHr15F0x** [comment]
> It would just be any input that is not a BLOCK_HASH_OR_TAG?
Yeah, that's the max we can do.

**Comment by fracek** [comment]
Yes the issue is like @Mirko-von-Leipzig said, the message is ambiguous. For example an hash of `""` returns the `invalid block hash` error, the same error I get when I pass for example `"0x4b6622b36e24ee164e4eeee6625d1698f79cda38ef17d70982c719442cad399"` (a well formed hash that doesn't match any block).

If I look at the spec you linked and at the [OpenRPC spec](https://spec.open-rpc.org/#content-descriptor-object) it looks like since `"result"` doesn't have a `"required": true` attribute then returning `"result": null` would still conform to it? That would also be inline with how other chains behave.

**Comment by CHr15F0x** [comment]
For sure we can distinguish between a malformed and unknown hash for txn|bock|whatnot. Now the question remains if Starkware want to reflect it in their spec through separate error codes or other means. I'll get back to you about this.

**Comment by CHr15F0x** [comment]
The latest starknet RPC-JSON [spec](https://github.com/starkware-libs/starknet-specs/blob/v0.2.1-rc1/api/starknet_api_openrpc.json) does not distinguish between malformed and unknown hash but it is assumed that a well formed block hash is a valid felt.

Pathfinder checks if a block hash is a valid felt and that is the most we can do right now.
A hash of `""` returns json rpc error `-32602` ([`invalid params`](https://www.jsonrpc.org/specification#error_object)) while a well formed hash (ie. which is at least a valid felt too) returns `24` (`Block not found`).
