### ISSUE TITLE
Bug: misleading hex parsing error message

### ISSUE THREAD

**Issue by xJonathanLEI** [eqlabs/pathfinder#365]
Currently `HexParseError::InvalidLength` always assumes an expected length of `64`:

https://github.com/eqlabs/pathfinder/blob/24c307f0fe050248287c3df95e6285b23267de80/crates/stark_hash/src/hash.rs#L336

which is not true. I found out about this when getting this confusing error message:

`More than 64 digits found: 64 at line 1 column 336`

**Comment by CHr15F0x** [comment]
Looks like the error variant always carries hex string len value which excludes the optional `0x` prefix.
Nice catch!

**Comment by xJonathanLEI** [comment]
@CHr15F0x Looks like that's actually not the issue. The length being compared is the length after the prefix is stripped.

It's rather that the expected length of `64` is hard-coded, while the actual expected length can be different from `64` (in my case it's actually `32`).

I submitted a fix in #366.
