### ISSUE TITLE
Bug: significant delay when querying a new block

### ISSUE THREAD

**Issue by xJonathanLEI** [eqlabs/pathfinder#373]
## Description

When polling for the latest block through `starknet_getBlockByHash` with the `latest` tag, the first query for a new block is always significantly slower. Subsequent requests are fast again.

## Steps to reproduce

_(Update: a Rust tool has been created for this: https://github.com/eqlabs/pathfinder/issues/373#issuecomment-1152874611)_

Run this script against a fully synced node over `alpha-goerli`:

```sh
#/!bin/sh

while true
do
    time curl \
        -H "Content-Type: application/json" \
        -d '{"method":"starknet_getBlockByHash","params":["latest"],"jsonrpc":"2.0","id":1}' \
        http://node.url 2>/dev/null \
        | jq ".result.block_number"
done
```

## Expected result

Response time should be similar whether a new block is imported or not.

## Actual result

```log
235357          
                                                                      
real    0m0.056s
user    0m0.023s                                                      
sys     0m0.011s                                                      
235357          
                                                                      
real    0m0.056s
user    0m0.022s                                                      
sys     0m0.005s                                                      
235357          
                                                                      
real    0m0.059s
user    0m0.022s                                                      
sys     0m0.009s                                                      
235358          
                                                                      
real    0m0.988s
user    0m0.033s                                                      
sys     0m0.000s                                                      
235358          
                                                                      
real    0m0.026s
user    0m0.030s                                                      
sys     0m0.004s 
```

**Comment by Mirko-von-Leipzig** [comment]
Thanks for the report. A 20x increase does seem excessive. We're looking into this, but in the mean time could you help us rule-out database write locking?

If you could you re-run the test with WAL mode enabled. To enable WAL,
```
sqlite3 github.db 'PRAGMA journal_mode=WAL;
```
but note that you need to do this while the node is running.

**Comment by Mirko-von-Leipzig** [comment]
We think its got to do with the kernel flushing the database cache during a block write, causing the first query to load from disk instead of RAM i.e. being slow. Unfortunately its proving difficult to validate this locally as we can't replicate this cache flush scenario.

We've also noticed that our sql query for `get_block(latest)` is reading a lot more data than it should which is exhasterbating this issue as it therefore requires a much larger cache size. I've created a branch [latest_delay_test_fix](https://github.com/eqlabs/pathfinder/tree/latest_delay_test_fix) which contains an attempt at a more optimal sql query.

Could you try test out this change? If you're using docker you'll unfortunately need to build the image manually -- we don't have the facility to generate non-release images yet :(.

**Comment by xJonathanLEI** [comment]
Let me test both. It's fine I build custom pathfinder images all the time, mainly to change the hard-coded poll interval to spam the sequencer more lol.

**Comment by xJonathanLEI** [comment]
For the first one, I `docker exec`'ed into the container and ran:

```sh
$ sqlite3 goerlie.sqlite 'PRAGMA journal_mode=WAL;'
wal
```

Then ran the same shell script:

```log
236142

real    0m0.056s
user    0m0.026s
sys     0m0.008s
236142

real    0m0.056s
user    0m0.026s
sys     0m0.008s
236143

real    0m0.786s
user    0m0.028s
sys     0m0.007s
236143

real    0m0.027s
user    0m0.031s
sys     0m0.004s
236143

real    0m0.043s
user    0m0.035s
sys     0m0.000s
```

Looks like it's still significant slower, but a little bit better than before?

**Comment by xJonathanLEI** [comment]
Another test: using the said branch and building a fresh image on a clean repo (`git clean -dfx`) with no cache.

And running the same script (against the same `goerli.sqlite` file, which I guess already have `journal_mode` set to `wal`?):

```log
236154

real    0m0.057s
user    0m0.028s
sys     0m0.004s
236154

real    0m0.059s
user    0m0.028s
sys     0m0.008s
236155

real    0m1.087s
user    0m0.030s
sys     0m0.003s
236155

real    0m0.025s
user    0m0.023s
sys     0m0.009s
236155

real    0m0.046s
user    0m0.023s
sys     0m0.008s
236155

real    0m0.024s
user    0m0.028s
sys     0m0.004s
```

Looks fixed :)

**Comment by xJonathanLEI** [comment]
Waittttt I just realized you had a typo in your sqlite command `goerliE.sqlite`.

So my first test didn't actually change the journal mode. Instead it created another empty sqlite database lol. So the first test was pointless.

But then my second test confirmed that your fix works :)

**Comment by xJonathanLEI** [comment]
I checked the code of the fix. So before this fix the node uses an `ORDER BY`, but IIUC that shouldn't be an issue as long as the block number is an index key?

**Comment by xJonathanLEI** [comment]
For context my server is rocking a Samsung 980 Pro NVMe SSD so read/write IO performance shouldn't be an issue. It's also not running inside a hypervisor (only Docker).

**Comment by Mirko-von-Leipzig** [comment]
Thanks that's really good info to have! No typo in my command though 🤔 Setting the WAL was unlikely to be a fix as in order for that to be a problem the timing of your query would matter i.e. you would need to query at the exact moment we are writing which would make your tests really inconsistent (which didn't seem to be the case).

> I checked the code of the fix. So before this fix the node uses an ORDER BY, but IIUC that shouldn't be an issue as long as the block number is an index key?

Yeah that's what we thought as well when we wrote it. However, upon investigating the resulting sqlite bytecode we noticed that it was reading the entire row while it was searching. We think its a missed sqlite optimisation.

In Rust pseudo code, it was doing something like the following:
```Rust
let mut latest = Block::GENESIS;
for row in blocks_table.rows {
    let (hash, number, root, timestamp, gas_price, sequencer_address) = row.read_fields();

    if number > latest.number {
        latest.hash = hash;
        latest.number = number;
        latest.root = root;
        ... etc
    }    
}
```
whereas the change forces it to first search for the maximum block number and only then read the actual block data (once). So a lot less reading of data.
```Rust
let mut latest = 0;
for row in blocks_table.rows {
    let number = row.get_number();
    latest = latest.max(number);
}
let row = blocks_table.rows[latest];
let latest_block = {
    hash: row.hash;
    number: row.number;
    root: row.root;
    ... etc
};
```

**Comment by xJonathanLEI** [comment]
For the typo I was talking about the file name. It should be `goerli` not `goerlie` lol.

**Comment by xJonathanLEI** [comment]
Nice and thanks for the detailed explanation!!

**Comment by Mirko-von-Leipzig** [comment]
Also unfortunately, I don't think its fixed?
```
real    0m1.087s
user    0m0.030s
sys     0m0.003s
236155
```
Its `1.087s` which I also misread as `0.087s`

**Comment by xJonathanLEI** [comment]
Wait... I also misread. OR I copied the wrong text. Lemme try again sorry.

**Comment by xJonathanLEI** [comment]
Same result oops. So it's not fixed unfortunately.

**Comment by Mirko-von-Leipzig** [comment]
Thanks for confirming. Back to the drawing board I suppose :)

**Comment by Mirko-von-Leipzig** [comment]
Could you test querying a an existing block number instead of `latest`?

**Comment by xJonathanLEI** [comment]
OK this gets more complicated... So instead of using the bash script I created a quick and dirty Rust program for this:

https://github.com/xJonathanLEI/pathfinder-perf-issue

**Comment by xJonathanLEI** [comment]
This should be more accurate as it gets rid of bash and curl overhead. I just tried running it (at [this commit](https://github.com/xJonathanLEI/pathfinder-perf-issue/commit/31ddbac7cbc65ccfb9298e33e1e47a9bbd92df5d)) against the SQL fix branch.

```log
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 5ms
Block: #236257. Time: 47ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 3ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 5ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 4ms
Block: #236257. Time: 5ms
Block: #236258. Time: 1079ms
```

Looks like it's not just 20x difference... The difference was underestimated before presumably due to bash and curl overhead. It's more like a 200x difference.

**Comment by Mirko-von-Leipzig** [comment]
Thanks that's very useful!

**Comment by xJonathanLEI** [comment]
And I just updated the code (to [this commit](https://github.com/xJonathanLEI/pathfinder-perf-issue/commit/c2f5d40cea3d8e6b70532506e239d6c2e5f62c98)) to:

1. find the current head block number
2. poll for the next block **by number** until it exists

And here's the result:

```log
Current block number: #236265, Time: 8ms
Querying for the next block #236266 directly
Block: #236266. Time: 1134ms
```

**Comment by xJonathanLEI** [comment]
Since I'm polling by number I guess the SQL fix doesn't matter anymore.

**Comment by xJonathanLEI** [comment]
Added a loop (at [this commit](https://github.com/xJonathanLEI/pathfinder-perf-issue/tree/ee703ccfbf996d3c3e72e9b9c08c509ef756f24d)) to show it's consistent:

```log
Current block number: #236268, Time: 13ms
Querying for the next block #236269 directly
Block: #236269. Time: 1134ms
Current block number: #236269, Time: 4ms
Querying for the next block #236270 directly
Block: #236270. Time: 1033ms
Current block number: #236270, Time: 4ms
Querying for the next block #236271 directly
Block: #236271. Time: 1035ms
Current block number: #236271, Time: 5ms
Querying for the next block #236272 directly
Block: #236272. Time: 1034ms
Current block number: #236272, Time: 5ms
Querying for the next block #236273 directly
Block: #236273. Time: 934ms
```

**Comment by xJonathanLEI** [comment]
OK yet another test (at [this commit](https://github.com/xJonathanLEI/pathfinder-perf-issue/tree/820989adc13b5e6cb3247ce34efa32cebf27227d)): query random blocks that's mostly guaranteed to require a database read:

```log
Current block: #155535. Time: 7ms
Current block: #78393. Time: 5ms
Current block: #220109. Time: 7ms
Current block: #97502. Time: 8ms
Current block: #227018. Time: 5ms
Current block: #124640. Time: 6ms
Current block: #51641. Time: 5ms
Current block: #177821. Time: 5ms
Current block: #122606. Time: 4ms
Current block: #187124. Time: 7ms
```

So it looks like this bug only affects latest blocks.

I restarted my node for this test and the result is the same. So no it's not because those blocks were previously queried.

**Comment by xJonathanLEI** [comment]
You said you're not able to reproduce this behavior on your side, is your node being used by other people/services? If that's the case maybe other services did the first query before you do?

**Comment by xJonathanLEI** [comment]
Oh s**t... Just in case I changed the sqlite journal mode to `wal` (this time without the typo!!) and re-ran all the tests above.

Then the issue is GONE IN ALL 4 TESTS.

So I guess it _IS_ because of database write-locking after all.

It all began with a typo...

**Comment by Mirko-von-Leipzig** [comment]
Do you know if any of these tests were with WAL enabled? Just want to definitely rule that out, since the typo may have ...
 It can reset when the node restarts. If not could you try enable it while the node is running and test again?

**Comment by Mirko-von-Leipzig** [comment]
Okay great. We are looking into providing a config option to enable WAL mode. Its not on by default currently because it can wreak havoc in some hardware configurations.

**Comment by xJonathanLEI** [comment]
Is there a chance pathfinder supports alternative database backends?

**Comment by Mirko-von-Leipzig** [comment]
Currently not at all; and it is very unlikely to. Our current opinion is that being database agnostic isn't really possible in any performant manner. One ends up with an ORM which leaves a lot of performance on the table and we would essentially have to support performance issues (like this one) across multiple backends.

Another concern is that other common databases aren't embedded and are therefore not really the same thing as sqlite.

We also don't see a benefit for doing so. What would be your use case? Or are you hoping other databases are more performant?

**Comment by xJonathanLEI** [comment]
Understood. I was just hoping another database would be more performant lol

**Comment by koivunej** [comment]
@xJonathanLEI I think we've made a number of releases (or just one) with things affecting this:
- #347
- #405 

Do you still have issues with `--sqlite-wal true` configuration..?

**Comment by Mirko-von-Leipzig** [comment]
Closing as I think this has been resolved by `--sqlite-wal true`.
