### ISSUE TITLE
Crash report: pk constraint failure

### ISSUE THREAD

**Issue by tarrencev** [eqlabs/pathfinder#381]
Ran into this error while running pathfinder:

```
2022-06-14T12:39:49.772117Z  INFO At head of chain poll_interval=30s
2022-06-14T12:39:52.776640Z  INFO Updated StarkNet state with block 239569
2022-06-14T12:40:20.301640Z  INFO At head of chain poll_interval=30s
2022-06-14T12:40:30.941830Z ERROR Sync process ended unexpected with: Err(Update L1 state with blocks Some(239497)-Some(239497)

Caused by:
    0: Insert update
    1: Insert L1 state update
    2: UNIQUE constraint failed: l1_state.starknet_block_number
    3: Error code 1555: A PRIMARY KEY constraint failed)
```

**Comment by Mirko-von-Leipzig** [comment]
Hmm. We've had a few reports of this happening in the past, but have never had enough data to properly track it down.

Did the sync process restart? 

If yes, did it continue working? 

If no, do you have a copy of the database still?

**Comment by Mirko-von-Leipzig** [comment]
Oh and what L1 node are you using?

**Comment by tarrencev** [comment]
> Hmm. We've had a few reports of this happening in the past, but have never had enough data to properly track it down.
> 
> Did the sync process restart?
> If yes, did it continue working?

The service crashed and was recreated. The sync seems to have continued working ok from there.

> Oh and what L1 node are you using?

I'm using an alchemy endpoint
