### ISSUE TITLE
Support sqlite `WAL` mode

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#384]
Sqlite's [WAL](https://sqlite.org/wal.html) mode allows database reads to continue while the database is locked by a write. It does this by generating an journal file for the write, which eventually gets merged back into the main database file.

This improves the RPC read performance during writes -- where currently our sync process effectively locks the database for (up-to) several seconds.

However WAL mode does come with some caveats.

Configuration should be a boolean flag to allow us to change the default behaviour while still letting the user specify `on`|`off` if they want a specific mode.

The initial shipping release should default to `off` but mark it as something which will default to `on` in a newer release.

An (incomplete) list of todos:
- [ ] wal configuration item
- [ ] support wal in database
  - [ ] enable / disable wal
  - [ ] configure wal journal
    - [ ] max journal file size
    - [ ] investigate other settings
- [ ] document extensively with relevant links

**Comment by koivunej** [comment]
Related:
- https://www.sqlite.org/pragma.html#pragma_journal_mode
- https://www.sqlite.org/pragma.html#pragma_journal_size_limit
