### ISSUE TITLE
Issues with `starknet_getEvents`

### ISSUE THREAD

**Issue by fracek** [eqlabs/pathfinder#390]
Sorry for opening the issue here but I don't know where to report issues with the RPC spec. I also wanted to hear your opinion on this.

I'm using the `getEvents` API but IMHO there are some flaws in its design that make it difficult to use:

 * Missing `log_index` field. This field should contain the log index in the block so that logs can always be sorted back.

These are minor things:

 * Can only specify `fromBlock` and `toBlock` but not `blockHash`. Once the network can reorg this means devs will have to check the block hash in the response to know if the events are relative to the block they need or another block.
 * Can only specify one address. It would be nice to be able to specify an array of addresses.
 * Can only specify one topic value. I don't use this much in practice but it's nice to have.

**Comment by Mirko-von-Leipzig** [comment]
I'll pass this feedback on to StarkWare and see what they say (they own the JSON-RPC specification).

Will report back once I've heard something.

**Comment by fracek** [comment]
As I was helping out with Isaac I noticed that the lack of `log_index` and only one topic per request make it impossible to build a reliable indexer. Given event `A` and event `B`, it's impossible to know if in any given block `A` was emitted before `B` or the other way around.

**Comment by CHr15F0x** [comment]
@fracek refreshing the thread - how does the `0.2.1-rc1` api serve your needs right now wrt indexing? Can you please comment?

**Comment by fracek** [comment]
I haven't used the new rpc api yet so I can't comment.

**Comment by sergey-melnychuk** [comment]
Closing the issue for now. Please feel free to reopen if the issue is still relevant.
