### ISSUE TITLE
Error: Creating python process for call handling. Have you setup our Python dependencies?

### ISSUE THREAD

**Issue by luuvandai** [eqlabs/pathfinder#410]
![image](https://user-images.githubusercontent.com/20057908/175572229-f646114b-dbf6-4693-86b3-72c3d7952f8b.png)
I run node for StarkNet project but running for a while, I get this error. Can you guide me to handle it. Thanks

**Comment by Mirko-von-Leipzig** [comment]
Its usually one of the following problems:

### You haven't activated the python virtual environment

If you're using a python virtual environment to manage the python dependencies (which we recommend), then you need to have activated that virtual environment before running pathfinder. 
```
source .venv/bin/activate
```
where the above `.venv` path is where you placed it initially. People commonly have this in `pathfinder/py/.venv` or in `~/.env`.

### You updated the node, but didn't update the python dependencies

Updating the python dependencies is done by entering the python virtual environment and updating the python pip dependencies:
```
source .venv/bin/activate
PIP_REQUIRE_VIRTUALENV=true pip install -r requirements-dev.txt
```

**Comment by Mirko-von-Leipzig** [comment]
Hmm. I see we don't actually mention this python updating in our readme. I've create an [issue](https://github.com/eqlabs/pathfinder/issues/411) to update the readme with this information.
