### ISSUE TITLE
StarkHash max value is incorrect

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#49]
The maximum value for a StarkHash is currently set to 2^252-1 whereas it should be
```
2^251 + 17*2^192
```
This will require updating the tests and the assertion.

**Comment by Mirko-von-Leipzig** [comment]
@CHr15F0x I think you've fixed this?

**Comment by CHr15F0x** [comment]
Yep, lemme find the PR/commit.
