### ISSUE TITLE
How do I deploy a gateway node

### ISSUE THREAD

**Issue by leezijie** [eqlabs/pathfinder#522]
How do I deploy a gateway node?

Like https://alpha-mainnet.starknet.io/feeder_gateway/get_transaction?transactionHash=0x40cf42253768f26101cd4adbdd3c759cba3728cddc8c176b7c59da92f2b63d3.

Because I found that the data queried by the pathfinder node API was incomplete.Even query transactions do not have block height.

`{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "starknet_getTransactionByHash",
    "params": ["0x045a26b17d924ae24e9bab4eeb3968fcf65cfc52daa3126f044381f576dbabc6"]
    }`

`{
	"jsonrpc": "2.0",
	"result": {
		"txn_hash": "0x45a26b17d924ae24e9bab4eeb3968fcf65cfc52daa3126f044381f576dbabc6",
		"contract_address": "0x549bbba185507b01c94a31da244145635a689b35eec76d5494f5b84978fafcd",
		"entry_point_selector": "0x15d40a3d6ca2ac30f4031e42be28da9b056fef9bb7357ac5e85627ee876e5ad",
		"calldata": [
			"0x1",
			"0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
			"0x83afd3f4caedc6eebf44246fe54e38c95e3179a5ec9ea81740eca5b482d12e",
			"0x0",
			"0x3",
			"0x3",
			"0x1e7501b398a7a88c8eda80e13ebc905d1ea8ea3f67558678a20c56ad8ba561c",
			"0x38d7ea4c68000",
			"0x0",
			"0x2"
		],
		"max_fee": "0xba72482dd000"
	},
	"id": 0
}`

**Comment by Mirko-von-Leipzig** [comment]
Sorry for the delay :)

Short answer: you cannot deploy a gateway node as there is no such node.

## Longer explanation
StarkNet is currently centralized and there is only a single point for a pathfinder node to get starknet data from -- this is the Sequencer gateway run by StarkWare. This will change in the future, but this is still a while awway. In other words, there is no gateway node, only the sequencer who's code is not publicly available.

## JSON-RPC API
It sounds more like you're unhappy with the information being provided by our API? We follow the official JSON-RPC specification provided by StarkWare.

We can make suggestions to the specification and

**Comment by leezijie** [comment]
> Sorry for the delay :)
> 
> Short answer: you cannot deploy a gateway node as there is no such node.
> 
> ## Longer explanation
> StarkNet is currently centralized and there is only a single point for a pathfinder node to get starknet data from -- this is the Sequencer gateway run by StarkWare. This will change in the future, but this is still a while awway. In other words, there is no gateway node, only the sequencer who's code is not publicly available.
> 
> ## JSON-RPC API
> It sounds more like you're unhappy with the information being provided by our API? We follow the official JSON-RPC specification provided by StarkWare.
> 
> We can make suggestions to the specification to improve it.
> 
> Currently you are missing the block ID when querying a specific transaction. Is there anything else you feel is missing?
> 
> You can also open an issue at the specification project: https://github.com/starkware-libs/starknet-specs. Otherwise I can also do it.

Thank you for your reply, I think it is necessary to return the block height when query the transaction details

**Comment by Mirko-von-Leipzig** [comment]
Yes that does make sense to me as well. I'll pass that information on to the specifications team.

**Comment by leezijie** [comment]
> Yes that does make sense to me as well. I'll pass that information on to the specifications team.

Great!

**Comment by Mirko-von-Leipzig** [comment]
Some feedback I got from the specification team. It sounds like it is not something they would add to transactions, but the data is present in the transaction receipt.

> Adding the block ID information to the transaction would mean that in the case of a re-org that information might be incorrect.
> In other words, the block id isn't an inherent part of the transaction definition.
>
> Note that it is part of the transaction receipt.
> This makes a bit more sense to me since it's part of the "transaction result" - where this transaction was executed.

**Comment by leezijie** [comment]
> Some feedback I got from the specification team. It sounds like it is not something they would add to transactions, but the data is present in the transaction receipt.
> 
> > Adding the block ID information to the transaction would mean that in the case of a re-org that information might be incorrect.
> > In other words, the block id isn't an inherent part of the transaction definition.
> > Note that it is part of the transaction receipt.
> > This makes a bit more sense to me since it's part of the "transaction result" - where this transaction was executed.

Starknet_getTransactionReceipt also sounds OK, but this interface does not currently return block height data either

**Comment by Mirko-von-Leipzig** [comment]
It should, under the common transaction properties.
