### ISSUE TITLE
BUG: GetEvents Broken

### ISSUE THREAD

**Issue by rzmahmood** [eqlabs/pathfinder#535]
Hello! I'm from Immutable and have been using the Infura Pathfinder Node implementation. It had been working fine, but now the request that previously worked, now results in an error:

```json
{
        "jsonrpc":"2.0",
	"method":"starknet_getEvents",
         "params": [
              {"fromBlock": 62048, "toBlock":63048, "page_size": 1000, "page_number": 0}
         ],
	"id":1
}
```
This results in the following error:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32602,
        "message": "expected value at line 1 column 15"
    },
    "id": 1
}
```

This is blocking our systems. I have been using the Postman workspace as the source of truth, but it is not updated if any changes have been made ( https://www.postman.com/starknet-edu/workspace/starknet-edu/request/20082312-3f1abb60-e3d9-486c-a517-355077e29a47 )

**Comment by kkovaacs** [comment]
Looks like Infura has upgraded their deployment to a version that follows the v0.1.0 of the Starknet JSON-RPC specification: https://github.com/starkware-libs/starknet-specs/releases/tag/v0.1.0

In that version the `starknet_getEvents` method has been changed to receive block ids in the `fromBlock` and `toBlock` event filter properties, so now your query would have to be something like this:

```json
{
        "jsonrpc":"2.0",
	"method":"starknet_getEvents",
         "params": [
              {"fromBlock": {"block_number": 62048}, "toBlock": {"block_number": 63048}, "page_size": 1000, "page_number": 0}
         ],
	"id":1
}
```

Would you mind trying the above?

**Comment by Mirko-von-Leipzig** [comment]
As @kkovaacs said, its likely that Infura updated their pathfinder node(s) from v.2.x to at least v0.3.0. This was a breaking update which aligned pathfinder with version v0.1.0 of the JSON-RPC specification.

You can read more details about this in the [v0.3.0 release notes](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha).

**Comment by rzmahmood** [comment]
Thanks team, closing this. Will consider how we can better manage this in the future
