### ISSUE TITLE
No reply from RPC when `id` field is missing

### ISSUE THREAD

**Issue by CHr15F0x** [eqlabs/pathfinder#567]
For example, this works:

```bash=
#! /usr/bin/env bash
set -e;
set -o pipefail;

function rpc_call() {
     printf "Request:\n${1}\nReply:\n"
     curl -s -X POST \
          -H 'Content-Type: application/json' \
          -d "${1}" \
          http://127.0.0.1:9545
     printf "\n\n"
}

rpc_call '{"jsonrpc":"2.0","id":0,"method":"starknet_getStateUpdate","params":[{"block_number":1234}]}'
```
This does not, no reply is present:
```bash=
rpc_call '{"jsonrpc":"2.0","method":"starknet_getStateUpdate","params":[{"block_number":1234}]}'
```

**Comment by koivunej** [comment]
I wonder if updating jsonrpsee would help?

**Comment by CHr15F0x** [comment]
Just checked with a small test server using `jsonrpsee 0.15.1` and the issue persists.

**Comment by CHr15F0x** [comment]
According to the [json RPC specification](https://www.jsonrpc.org/specification#request_object):
- if a _request_ does not contain the `id` field, it is a _notification_:
    > id
An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. (...)
- [a notification does not result in a reply](https://www.jsonrpc.org/specification#notification):
    > A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.
    >
    > Notifications are not confirmable by definition, since they do not have a Response object to be returned. As such, the Client would not be aware of any errors (like e.g. "Invalid params","Internal error").
- which means that this is **not a bug** and behavior is consistent with the spec.
