### ISSUE TITLE
Tracking issue for JSON-RPC v0.2.1

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#586]
Tracking issue for supported [v0.2.1-rc1](https://github.com/starkware-libs/starknet-specs/tree/v0.2.1-rc1/api) of the JSON-RPC specification.

## Main API
- [x] #588
- [x] #589
- [x] #590
- [x] #591
- [x] #592
- [x] #593
- [x] #594
- [x] #595
- [x] #596
- [x] #597
- [x] #598
- [x] #599
- [x] #600
- [x] #601
- [x] #602
- [x] #603
- [x] #604
- [x] #605
- [x] #606
- [x] #607

## Write API
- [x] #608 
- [x] #609
- [x] #610
- [x] #656
- [x] #678

## Misc
- [x] Update our readme, including creating correct playground links.
- [x] #629 
- [x] #626 

## Fixes
- [x] #673 

## Fork-less rpc versioning (~~deferred~~ won't fix)
~~These are _nice to have asap_ but not blocking the release~~
EDIT: Perf issues detected, abandoning.
- [x]  #643 
- [x] #644

**Comment by sergey-melnychuk** [comment]
Fix of the spec that is necessary to produce basic DTO code generation: https://github.com/starkware-libs/starknet-specs/pull/56
