### ISSUE TITLE
The discord url is invalid 

### ISSUE THREAD

**Issue by zhengwen-infstones** [eqlabs/pathfinder#616]
I used the https://discord.com/invite/QypNMzkHbc to join the discord, but after I click the "join starknet", nothing happend.
![image](https://user-images.githubusercontent.com/105617959/190578787-9805de6d-147a-4017-a7ae-f50975ca3888.png)

Is there any new invite URL?
thank you

**Comment by Mirko-von-Leipzig** [comment]
We've double checked, but that link is still correct. Which makes sense as its showing you the invite page.

I'm unsure what would cause this; some discord / website / browser weirdness? Maybe you are already part of the StarkNet server? Although the link still takes me there despite me already having joined the server.

Alternatively, here is a [new temp link](https://discord.gg/hJs99VvK) which will expire in one week from now.

**Comment by Mirko-von-Leipzig** [comment]
Feel free to re-open the issue if you are still unable to join the discord.
