### ISSUE TITLE
Failed to create a file in /usr/share/pathfinder/data. 

### ISSUE THREAD

**Issue by sing1ee** [eqlabs/pathfinder#627]
I use docker-compose to run starknet node. got errors:
```shell
pathfinder-starknet-node-1 exited with code 1
pathfinder-starknet-node-1  | 2022-09-23T02:46:58.788792Z  INFO 🏁 Starting node. version="v0.3.5"
pathfinder-starknet-node-1  | Error: Failed to create a file in /usr/share/pathfinder/data. Make sure the directory is writable by the user running pathfinder.
pathfinder-starknet-node-1  |
pathfinder-starknet-node-1  | Caused by:
pathfinder-starknet-node-1  |     Permission denied (os error 13)
```

**Comment by Mirko-von-Leipzig** [comment]
As the error message says - does the user running pathfinder have access rights (specifically writing) to the `/usr/share/pathfinder/data` folder?

What often happens is that you create the folder as root and then try run it as your non-admin account. This fails because your non-admin account does not have access rights to that folder.

**Comment by sing1ee** [comment]
I run docker under uid=1000 and gid=1000, and I also check Dockerfile that create dir '/usr/share/pathfinder/data' with uid=1000 and gid=1000, too.

**Comment by Mirko-von-Leipzig** [comment]
Hmm. That's.. unexpected - we're unable to replicate this, but we're investigating.

**Comment by sergey-melnychuk** [comment]
Is this still relevant?

What are the permissions for the `/usr/share/pathfinder/data` directory?

https://askubuntu.com/questions/265381/how-to-make-a-directory-permanently-writable

**Comment by sergey-melnychuk** [comment]
Closing the issue for now. Please feel free to reopen if the issue is still relevant.
