### ISSUE TITLE
StarkNet 0.10.1 support

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#628]
Tracking issue for the StarkNet 0.10.1 update.

The following changes are applicable to pathfinder:
- new `DEPLOY_ACCOUNT` transaction type
- gateway API changes
  - `entry_point_type` removed from invoke transactions
  - `entry_point_selector` removed from V1 invoke transactions
  
The gateway changes can be handled by making the field optional for the duration of the transition.

These fields are removed because they are redundant - so maybe we can fill in this "missing" data for v0.1 RPC queries? We will also have to deviate from the specification by adding the new transaction type to the enum list.

We can also consider a migration to remove these fields from existing transactions, but that might be too costly at this point.

**Comment by kkovaacs** [comment]
Starkware Notion document with the details: https://starkware.notion.site/starkware/StarkNet-0-10-1-07b5c6d433464c61bf035037b8113b7b
