### ISSUE TITLE
Can you specify a different background set of genes? To compare 2 lists of genes

### ISSUE THREAD

**Issue by apelin20** [eqlabs/pathfinder#653]
I have protein interaction data telling me which host preys/proteins are targeted by a virus. I then have additional data which divides the list of targeted proteins into those responsible for a phenotype (n=319) those that aren't contributing to a phenotype (n=2118). How can I find out which pathways (ex KEGG) that are enriched in the phenotype associated gene list compared no the gene list not contributing to the phenotype? I have found a similar post on biostars which suggests setting the union of both lists as background.

Is it possible to supply a custom background set to pathfindR?

**Comment by Mirko-von-Leipzig** [comment]
Obi-wan: "These are not the ~~droids~~ genes you are looking for".

This pathfinder project is a node for the StarkNet blockchain. And while of course you are welcome to browse and use our project, we unfortunately cannot help with genetic analysis.

A brief github search, I found [GideonMarsh/Genetic-Pathfinder](https://github.com/GideonMarsh/Genetic-Pathfinder) and [QualityHammer/Genetic-Pathfinder](https://github.com/QualityHammer/Genetic-Pathfinder) which maybe are the ones you want?
