### ISSUE TITLE
declare contract

### ISSUE THREAD

**Issue by muchenshou** [eqlabs/pathfinder#744]
Hi,  when I call starknet_addDeclareTransaction, I get this error
{ error:
   'StarknetError { code: NotPermittedContract, message: "The contract class attempted to be deployed is not permitted." }' }

**Comment by Mirko-von-Leipzig** [comment]
That's all the information we get back from the StarkNet gateway 🤷 We simply pass on the command to the gateway - no direct pathfinder involvement at all.

Are you perhaps trying this on mainnet? I think classes have to be whitelisted there. 

You can also try ask on the StarkNet discord or telegram groups.
