### ISSUE TITLE
Support `pending` blockid in `get_proof`

### ISSUE THREAD

**Issue by pscott** [eqlabs/pathfinder#779]
Currently, `BlockID::Pending` is not supported in `get_proof` (see #736).

Some ["unfortunate database fiddling"](https://github.com/eqlabs/pathfinder/pull/726#discussion_r1030829310) is required to add support for pending blocks.

**Comment by Mirko-von-Leipzig** [comment]
We have decided not to support this for two reasons:

1. At some point (soonish) the state commitment root will be removed from the pending information. This would make this pending proof meaningless.
2. Pending information is also meant as a stop-gap which means it will not be around for forever.
