### ISSUE TITLE
starknet_getEvents filter 'latest'

### ISSUE THREAD

**Issue by tabaktoni** [eqlabs/pathfinder#788]
Expected behavior:
When filtering from the 'latest' to the 'latest' block expected result is to get the latest block events.

Actual behavior:
You will get events from all blocks.

API request example (unexpected behavior)
```json
{
    "jsonrpc": "2.0",
    "method": "starknet_getEvents",
    "params": {
        "filter": {
            "from_block": "latest",
            "to_block": "latest",
            "chunk_size": 1000
        }
    },
    "id": 0
}
```

starknet js example 1 (unexpected behavior)
```js
    let events = await provider.getEvents({
        from_block: 'latest',
        to_block: 'latest',
        chunk_size: 1000
    })
```

starknet js example 2 (this will produce the expected behavior)
```ts
    let block = await provider.getBlock('latest');

    let events = await provider.getEvents({
        from_block: {
            block_number: block.block_number
        },
        to_block: {
            block_number: block.block_number
        },
        chunk_size: 1000
    })
```

Summary:
example 1 and example 2 should produce the same result.

**Comment by Mirko-von-Leipzig** [comment]
This [code](https://github.com/eqlabs/pathfinder/blob/main/crates/rpc/src/v02/method/get_events.rs#L143) is incorrect and leads to this bug.

We map `latest` to `None` which in turn gets interpretted by our database code differently depending on whether its the `to_block` or `from_block`.
```
to_block   == None -> to_block   = Genesis // this is the bug in this instance
from_block == None -> from_block = latest  // this is correct, but is what the mapping `None` above relies on
```
