### ISSUE TITLE
pathfinder_getProof, len of edgeProof may be off by one

### ISSUE THREAD

**Issue by FawadHa1der** [eqlabs/pathfinder#807]
for the request {
	"jsonrpc":"2.0",
	"method":"pathfinder_getProof",
    "params": [{"block_number": 352844}, "0x6fbd460228d843b7fbef670ff15607bf72e19fa94de21e29811ada167b4ca39", ["0x0206F38F7E4F15E87567361213C28F235CCCDAA1D7FD34C9DB1DFE9489C6A091"]],
 	"id":1
}

the response is 

        "contract_data": {
            "class_hash": "0x21a7f43387573b68666669a0ed764252ce5367708e696e31967764a90b429c2",
            "nonce": "0x0",
            "root": "0x54d89b946081c6556161b34bcd7838c501575a3e9dc3d1d38a4438107b6b8fb",
            "contract_state_hash_version": "0x0",
            "storage_proofs": [
                [
                    {
                        "edge": {
                            "path": {
                                "value": "0x206f38f7e4f15e87567361213c28f235cccdaa1d7fd34c9db1dfe9489c6a091",
                                "len": 251
                            },
                            "child": "0x1e240"
                        }
                    }
                ]
            ]
        }

for the path 0x206f38f7e4f15e87567361213c28f235cccdaa1d7fd34c9db1dfe9489c6a091, Len is 251, I presume this is the length of value of edge path, if thats the case should it not be 250? (just by the simple conversion to binary and removing the leading zero bits)

**Comment by Mirko-von-Leipzig** [comment]
251 is correct. The length isn't literally the binary length of the number, but rather the length of the path covered - i.e. eading zero bits still convey information. The length also forms part of the hash for an edge node so you can't just change it.

**Comment by FawadHa1der** [comment]
Thanks for the clarification
