### ISSUE TITLE
pathfinder_getProof, starknet_getStorageAt seem unoptimized for storage_vars returning structs

### ISSUE THREAD

**Issue by FawadHa1der** [eqlabs/pathfinder#808]
Currently starknet_getStorageAt only returns a felt storage_var address returning a struct in actual cairo code. It seems its returning the first member and if you append the address by one it will return the second member of the struct. As an example for the following request, it will be have to be repeated a number of times to get all the values of the struct for addresses 0x3284999a2939a8b54b2831813deb324170904a9a5145470eca917d66eb69708, 0x3284999a2939a8b54b2831813deb324170904a9a5145470eca917d66eb69709 so on and so forth

{"jsonrpc":"2.0","id":"0000","method":"starknet_getStorageAt","params":["0x048a64f708011fb5089778204f37d6111bd9bbac0fe4b6e7851292b8cbeeb6ef", "0x3284999a2939a8b54b2831813deb324170904a9a5145470eca917d66eb69708", "latest"]}

which seems inefficient but which also makes the pathfinder_getProof part also inefficient, we have to pass the paths for every member of the struct and then of course verification also takes a long time to verify every member of the struct. Not sure it can be optimized, but may be there is a way.....

**Comment by Mirko-von-Leipzig** [comment]
The [storage key](https://github.com/eqlabs/pathfinder/blob/main/pathfinder_rpc_api.json#L43-L54) input param is an array so you can pass in all the keys you want into a single query.

You'll still need to verify all of them (they each get their own output currently), but at least its a single query.

Also consider that pathfinder (or the starknet state) has no concept of structs or arrays or anything like that. All it knows about are keys.

**Comment by FawadHa1der** [comment]
It was a long shot I know, thought I would try if there was a faster way, makes sense, thanks Mirko.
