### ISSUE TITLE
Ensure sqlite is using `pragma synchronous = normal`

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#810]
[#pragma synchronous](https://www.sqlite.org/pragma.html#pragma_synchronous) controls how often changes are written to disk. This option should be set to `normal` but we don't currently explicitly set this.

In addition, we should also check `fullsync` and `checkpoint_fullsync` as the sqlite docs suggest.

Credit: @koivunej

**Comment by kkovaacs** [comment]
`synchronous` defaults to 2, which is sub-optimal for our use-case if we're using WAL mode, so I've added some code that sets it to `normal`.

`fullfsync` and `checkpoint_fullfsync` seem to be MacOS-only, so we're not touching those values.

Thanks @koivunej!

**Comment by Mirko-von-Leipzig** [comment]
> `synchronous` defaults to 2, which is sub-optimal for our use-case if we're using WAL mode, so I've added some code that sets it to `normal`.
> 
> `fullfsync` and `checkpoint_fullfsync` seem to be MacOS-only, so we're not touching those values.
> 
> Thanks @koivunej!

Okay we should close this then?

**Comment by kkovaacs** [comment]
Yes, should be fixed on `main`.
