### ISSUE TITLE
Explore state trees and storage

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#820]
It would be good to get some statistics on the state tree over time. This will help us make decisions on how we can trade-off storage versus tree / diffs.

Our questions may evolve as we explore the data, but here are some starting questions:

1. How large is the tree at each block? Can we comfortably fit the latest tree in memory? How many nodes of each type are there? (the latter will let you calculate the first question).
2. What is the node diff count between each block?
3. How much storage do we save if we only store the trees for
    1. every     10th block
    2. every    100th block
    3. every  1 000th block
    4. every 10 000th block
4. If we do store only every Nth block, how much memory does it take to perform the state updates from `N` to `2N-1`? This would be required if we want to compute merkle proofs on the fly for historical blocks, or anything similar really.
5. What speed up does having an LRU have?
    
## Suggested approach

Create a tool which reads storage diffs from an existing database and applies them to a tree stored in memory (hashmap of some kind). This should allow you to determine the answers to (1) and (2), although (2) might be complex to get optimised..

(3) is probably easiest to answer by opening the existing trees in the database at the relevant blocks (don't forget to account for shared nodes).

**Comment by kkovaacs** [comment]
This has been mostly covered when implementing pruned mode and state reverts using state diff.
