### ISSUE TITLE
StarkNet `v0.11.0` tracking

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#822]
Tracking issue for StarkNet `v0.11.0` support. Changes are documented [here](https://docs.starknet.io/documentation/starknet_versions/upcoming_versions/) but we should still expect changes and more information over the coming days / weeks.

I'll start with a broad list of what is likely required and we can expand and refine it as more information becomes available. Once something is actionable, it would be nice to split it into a separate issue which is also tracked here.

## Cairo 1.0 and Sierra

Cairo 1.0 classes may now be deployed using Declare V2 transactions. We will have to store its Sierra IR representation (to hand out to users via JSON-RPC) but will also need to compile it to Cairo assembly. The latter is required to execute calls and estimate fee's in the VM.

- [x] #823
- [x] #824
- [x] #903 
- [x] #904 
- [x] #905 
- [x] #906 

## Declare V2

This new transaction type will permeate everywhere - RPC, gateway, sync, storage

## State commitment

The state commitment definition is changing from v0.11.0 onwards. It now includes a class hash commitment tree. Since this change takes effect from literally v0.11.0 onwards, we will need to parse the semver version of a block to calculate the state commitment hash.

~~A question I have - are historical classes included in this tree or is it new classes only? I imagine only Cairo v1 classes to be backwards compatible?~~ Indeed, [only Cairo v1 classes](https://github.com/eqlabs/pathfinder/issues/822#issuecomment-1381786399) are used.

- [x] #825
- [x] #826
- [x] #827
- [x] #895 

## JSON-RPC changes

Changes are already available for preview in the PRs since the last release. We will need to investigate how we can make v0.2 compatible with the upcoming v0.3 release.

On a positive note, at least we can remove v0.1.

- [x] #828
- [x] #830
- [x] #834
- [x] #855
- [x] #856
- [x] #857
- [x] #858
- [x] #859
- [x] #860
- [x] #861
- [x] #862
- [x] #863
- [x] #864
- [x] #865
- [x] #866
- [x] #867
- [x] #868
- [x] #869
- [x] #870
- [x] #871
- [x] #872
- [x] #873
- [x] #874
- [x] #875
- [x] #876 
- [x] #877
- [x] #879 
- [x] #885 
- [x] #887
- [x] #901 

## Gateway API

- [x] #839 
- [x] #854 
- [x] #899 
- [x] #912 

## Poseidon hash

Poseidon hash will be used in some places, but it is not yet clear where exactly.

- [x] #829 

## Breaking Release

Since this is a breaking release, it would be a good time to remove the deprecated items:
- [x] #791
- [x] #900 

## Misc

- [x] #919

## Release preparations

- [x] #902

**Comment by kkovaacs** [comment]
> A question I have - are historical classes included in this tree or is it new classes only? I imagine only Cairo v1 classes to be backwards compatible?

This was mentioned during the meeting -- only Cairo v1 classes are added to the classes tree.
