### ISSUE TITLE
Embed Sierra compiler

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#823]
Test out the Sierra compiler which I imagine is this [crate](https://github.com/starkware-libs/cairo/tree/main/crates/cairo-lang-sierra-to-casm). Some basic performance benchmarks would be useful to determine where we use this.

New classes are Sierra IR but we require Cairo assembly (CASM) to execute in the VM. The compiler will be used to compile Sierra to CASM.

We can do this in one of two ways:

1. on-the-fly as needed by call, estimate fee etc
2. for every new Sierra class as it arrives during sync

The performance tests will determine which one we choose. Its possible there is not yet enough test Sierra code to do this benchmarking properly, but we should be able to request some samples.

**Comment by CHr15F0x** [comment]
Looks like what we're looking for is implemented in [starknet-sierra-compile](https://github.com/starkware-libs/cairo/blob/main/crates/cairo-lang-starknet/src/starknet_sierra_compile.rs)
