### ISSUE TITLE
Support new `starknet_getEvents` event filter semantics for keys

### ISSUE THREAD

**Issue by kkovaacs** [eqlabs/pathfinder#834]
The JSON-RPC API has [changed](https://github.com/starkware-libs/starknet-specs/commit/e9415a91dbf08b480fc05bb985d7cf8a93a898bc) the representation and semantics of `keys` in the event filter structure.

Now `keys` is an array which "per key (by position), designate the possible values to be matched for events to be returned". Empty array designates 'any' value.

**Comment by kkovaacs** [comment]
- Filtering for key values have changed. The filter now looks like this: `[["key1_value1", "key1_value2"], [], ["key3_value1"]]`  
	- The meaning of this is `(key1 == "key1_value1" OR key1 == "key1_value2") AND (key3 == "key3_value1")`  
- We're currently full-text indexing Base64-encoded representation of key values for each event  
- Instead of base64 we should use base32 (without padding, all our keys are 32 bytes long) because FTS5 indexes are case-insensitive.  
- We should prefix each key value with the key index so that we can match on a particular value at a particular index (`01key1_value1`) and store the list of those values in the FTS5 table.  
- The filter expression above can be expressed as an FTS5 MATCH as:  
	- `("01key1_value1" OR "01key1_value2") AND ("03key3_value3")`  
- This has the advantage that we can still use a full-text index instead of multiple indexes for multiple columns in our database.  
	- The sqlite query planner has a limitation: it can use a single index per table. This means that we can't simply create an indexed column per key value -- the query planner probably won't be able to use it.  
	- The FTS5 index appears as a join in our query. This avoids the query planner limitation.  
	- We don't have to hard-code the number of keys to index in our DB schema.  
- base32 conversion  
  ``` base32
  use data_encoding::{BASE32_NOPAD, HEXLOWER_PERMISSIVE};
  
  fn main() {
      // key value
      let mut data = HEXLOWER_PERMISSIVE
          .decode(b"02EBBD6878F81E49560AE863BD4EF327A417037BF57B63A016130AD0A94C8EAC")
          .unwrap();
      // index
      data.push(0u8);
      let encoded = BASE32_NOPAD.encode(&data);
      println!("Encoded: {}", encoded);
  }
  base32 [main●] % cargo run      
  
      Finished dev [unoptimized + debuginfo] target(s) in 0.00s
       Running `target/debug/base32`
  Encoded: ALV322DY7APESVQK5BR32TXTE6SBOA336V5WHIAWCMFNBKKMR2WAA
  ```
- Storing the keys as base64/base32-encoded strings in the database has a large overhead. We could define SQLite functions instead that take a BLOB of 32-byte felts concatenated and computes the appropriate string representation for FTS5 use:  
	- space-separated list of base64-encoded felts for the old index  
	- space-separated list of base32-encoded `felt | index` values for the new index  
	- triggers can then use these functions in `INSERT INTO starknet_events_keys`

**Comment by Mirko-von-Leipzig** [comment]
Is sticking with the old `base64` just for backwards compat? I suppose a migration to change that to `base32` would be expensive and pointless as they'll get dropped with `v0.2`. I'm somewhat curious about the performance implications 😁

> We could define SQLite functions instead that take a BLOB of 32-byte felts concatenated and computes the appropriate string representation for FTS5 use

Is this somehow less overhead than doing it manually? I'm fine with doing it this way because it feels much more database agnostic without sacrificing perf (if I'm understanding correctly).

All-in-all I think this is a good plan.

**Comment by kkovaacs** [comment]
> I'm somewhat curious about the performance implications

I'm curious too... The point would be migrating the events table so that we only store keys in a binary BLOB (just as we do with data now) and use the FTS5 indexes only as a contentless index. This would somewhat lower the storage overhead we're having now with base64. We could also just use base32 in both FTS5 indexes. We'll see how long these migrations actually take...

> Is this somehow less overhead than doing it manually? I'm fine with doing it this way because it feels much more database agnostic without sacrificing perf (if I'm understanding correctly).

The point is being able to do the binary -> base32 transformation in the trigger itself so we don't have to store the base32 form of the keys in the table itself.

**Comment by kkovaacs** [comment]
Some preliminary results for the migration (complete migration, that involves re-creating the events table, indexes, the FTS5 index for JSON-RPC 0.2 semantics and the FTS5 index for JSON-RPC 0.3 semantics):

```
2023-01-18T11:42:44.784744Z  INFO pathfinder_storage::schema::revision_0024: Migrating events table, this may take a while row_count=55071327
2023-01-18T11:49:32.375625Z  INFO pathfinder_storage::schema::revision_0024: Re-created the starknet_events table and copied data
2023-01-18T12:07:18.863264Z  INFO pathfinder_storage::schema::revision_0024: Re-created the indexes for starknet_events
2023-01-18T12:12:13.685077Z  INFO pathfinder_storage::schema::revision_0024: Re-created event key index for starknet_events
2023-01-18T12:16:28.078140Z  INFO pathfinder_storage::schema::revision_0024: Created event key index with new lookup semantics for starknet_events
migrated in 2194.933429949s, size change: 15438786560
```

The migration also requires ~20GiB disk space for the WAL file alone.

**Comment by Mirko-von-Leipzig** [comment]
Hmm so 30 minutes + 20GiB on a near optimal system? Seems rough 😬

**Comment by kkovaacs** [comment]
It works reasonably well for mainnet at block 18870 though:

```
2023-01-18T13:11:33.392448Z  INFO pathfinder_storage::schema::revision_0024: Migrating events table, this may take a while row_count=7216320
2023-01-18T13:11:45.486070Z  INFO pathfinder_storage::schema::revision_0024: Re-created the starknet_events table and copied data
2023-01-18T13:12:02.971874Z  INFO pathfinder_storage::schema::revision_0024: Re-created the indexes for starknet_events
2023-01-18T13:12:12.950701Z  INFO pathfinder_storage::schema::revision_0024: Re-created event key index for starknet_events
2023-01-18T13:12:22.956096Z  INFO pathfinder_storage::schema::revision_0024: Created event key index with new lookup semantics for starknet_events
migrated in 66.208717439s, size change: 1906745344
```

**Comment by Mirko-von-Leipzig** [comment]
I'm wondering if we should do a minor version which does this in the background at least?

**Comment by kkovaacs** [comment]
Another option would  be finding out if we can just use alter table to change the keys column and maybe leave all existing indexes as is? I'll check if that works.

**Comment by kkovaacs** [comment]
Using ALTER TABLE is promising for mainnet:

```
2023-01-18T14:00:14.412655Z  INFO pathfinder_storage::schema::revision_0024: Migrating events table, this may take a while row_count=6962674
2023-01-18T14:00:32.116104Z  INFO pathfinder_storage::schema::revision_0024: Converted keys to BLOB in starknet_events
2023-01-18T14:00:42.034927Z  INFO pathfinder_storage::schema::revision_0024: Created event key index with new lookup semantics for starknet_events
migrated in 37.160294664s, size change: 499175424
```

**Comment by kkovaacs** [comment]
And for the testnet DB:

```
2023-01-18T14:16:13.927824Z  INFO pathfinder_storage::schema::revision_0024: Migrating events table, this may take a while row_count=55054172
2023-01-18T14:27:48.678984Z  INFO pathfinder_storage::schema::revision_0024: Converted keys to BLOB in starknet_events
2023-01-18T14:31:19.194321Z  INFO pathfinder_storage::schema::revision_0024: Created event key index with new lookup semantics for starknet_events
migrated in 1177.756226389s, size change: 4081516544
```

This would mean that we're keeping the old FTS5 index with the base64 encoded keys too.

The only way I thing we could make this faster is omitting the conversion of the `keys` column to BLOB -- which would be a shame I think, though that step seems to make up most of the cost of this migration.

**Comment by kkovaacs** [comment]
And finally: if we omit the conversion of the `keys` column to BLOB entirely and are effectively just adding a new FTS5 contentless index with the appropriate triggers to update it automatically (on a testnet db):

```
2023-01-20T14:05:44.301714Z  INFO pathfinder_storage::schema::revision_0024: Creating new index for event keys, this might take a while row_count=56162487
2023-01-20T14:10:14.621672Z  INFO pathfinder_storage::schema::revision_0024: Created event key index with new lookup semantics for starknet_events
migrated in 286.913032155s, size change: 805392384
```

**Comment by kkovaacs** [comment]
Another question is if we want to have a limit on the number of keys we're indexing. With the current scheme we're encoding the key index as an `u8` so that limits the number of keys we _can_ index to 256. However, I'm not sure it's even worth indexing that many keys, so we should maybe come up with a more reasonable limit?

**Comment by Mirko-von-Leipzig** [comment]
> Another question is if we want to have a limit on the number of keys we're indexing. With the current scheme we're encoding the key index as an `u8` so that limits the number of keys we _can_ index to 256. However, I'm not sure it's even worth indexing that many keys, so we should maybe come up with a more reasonable limit?

I suppose the question is, does it even matter? Don't most events only have a handful of keys and therefore limiting it doesn't really make a difference? But we can try be safer I guess and just set it to `10` or something?

**Comment by kkovaacs** [comment]
Frankly, if _most_ events only contain a handful of events then we're probably not saving anything by using a limit of `10` instead of `256`...

**Comment by Mirko-von-Leipzig** [comment]
> Frankly, if _most_ events only contain a handful of events then we're probably not saving anything by using a limit of `10` instead of `256`...

Agreed; the counter argument is that it is more secure against DoS accounts which spam events with many keys to slow down nodes 🤷 But I don't think its an issue, and should be a fairly simple thing to change if we need to in the future?
