### ISSUE TITLE
Crypto refactor

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#848]
Long term maintenence and refactoring notes from @mikdk. These are non-critical future work items.

- Create root stark_field crate with "felt" and "fieldelement", and overriding x86 with CryptoExperts custom assembly.
- stark_curve as now, replace one algorithm ("projective+affine") with the Bernstein one also used by ark-ff.
- stark_poseidon, compress constants, fix "thee" typo in README.
- For each crate, add README and docs to prep for possible [crates.io](http://crates.io/) release.

**Comment by kkovaacs** [comment]
Mostly already done by Michael. We've also decided not do do a crates.io release for now.
