### ISSUE TITLE
v0.3 `starknet_simulateTransaction`

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [eqlabs/pathfinder#887]
Pending [specification PR](https://github.com/starkware-libs/starknet-specs/pull/69).

**Comment by CHr15F0x** [comment]
Depends on #906

**Comment by kkovaacs** [comment]
Producing a `TransactionTrace` from the `TransactionExecutionInfo` object returned by `apply_state_updates()`: https://github.com/Shard-Labs/starknet-devnet/blob/804e391f61e7465ed85d9e7a6f2c1b6d16ca1742/starknet_devnet/starknet_wrapper.py#L802
