### ISSUE TITLE
Gateway client retry logic saturates at 1 hour sleep between retries

### ISSUE THREAD

**Issue by kkovaacs** [eqlabs/pathfinder#893]
Since this is now the multiple of the block time even on mainnet waiting for this long is somewhat unreasonable.

Could we safely decrease this to roughly match the expected block time on mainnet without adding too much additional pressure on the gateway?

**Comment by CHr15F0x** [comment]
Just for clarification: the retry logic [saturates at 1hr](https://github.com/eqlabs/pathfinder/blob/4ab915a830953ed6f02af907937b46cb447d9a92/crates/gateway-client/src/builder.rs#L388).

Those values mean:
```
base value == 2
factor == 15s
saturate at == 60 * 60 s
```
and the consecutive backoff intervals are calculated as:
```
Nth backoff interval = min( saturation backoff, (base^N) * factor )

Nth backoff interval = max( 1hr, (2^N)*15s )
```
which means that the sequence of backoff intervals in out retry logic is:
```
15s, 30s, 1m, 2m, 4m, ... 32m, 1hr, 1hr, 1hr, ...
```

Please see [here](https://github.com/eqlabs/pathfinder/blob/4ab915a830953ed6f02af907937b46cb447d9a92/crates/retry/src/lib.rs#L28), [here](https://github.com/eqlabs/pathfinder/blob/4ab915a830953ed6f02af907937b46cb447d9a92/crates/retry/src/lib.rs#L43) and [here](https://github.com/eqlabs/pathfinder/blob/4ab915a830953ed6f02af907937b46cb447d9a92/crates/retry/src/lib.rs#L49).

**Comment by kkovaacs** [comment]
Sure, makes sense based on the code. Thanks for the clarification.
