### ISSUE TITLE
handle new state updates

### ISSUE THREAD

**Issue by CHr15F0x** [eqlabs/pathfinder#899]
As described [here](https://docs.starknet.io/documentation/starknet_versions/upcoming_versions/#feeder_gateway)

TL;DR
- handle `replaced_classes`, ie. update the mapping `contract_address -> class_hash`
- `declared_classes` contains a mapping of new sierra class hashes vs their casm class hashes
- `old_declared_classes` is the former `declared_classes` which contains hashes of new cairo v0 declared classes

**Comment by kkovaacs** [comment]
I think this needs even more changes:

- We need to be able to track contract_address -> class_hash for any point in time, this needs storage changes.
- When applying state updates we'll need to take care of replaced classes since class replacement changes the state commitment for a contract.

**Comment by CHr15F0x** [comment]
Handling an equivalent of `l2::Event::NewContract` for a sierra class means that this task depends on #905

**Comment by Mirko-von-Leipzig** [comment]
I think this issue can now be closed?

**Comment by kkovaacs** [comment]
I  think yes, we have implemented this.
