### ISSUE TITLE
Update obsolete frozendict 1.2 dependency

### ISSUE THREAD

**Issue by DShaurin** [eqlabs/pathfinder#920]
With current python3.10 (release) Pathfinder doesn't start because of this old version of frozendict 1.2. Actually, it is from 2019.
Latest release is frozendict 2.3.5.
https://github.com/eqlabs/pathfinder/blob/2c6e344fe592f112d3a2b81160a0d6e6400379aa/py/requirements-dev.txt#L90

**Comment by Mirko-von-Leipzig** [comment]
@DShaurin I'm going to close this, as this is not something we can directly influence. I agree, its been a pita for us as well, and hopefully the next `cairo-lang` release improves the situation.

Feel free to re-open if you want to discuss it further.

**Comment by kkovaacs** [comment]
On my branch where I've upgraded `cairo-lang` to 0.11.0a0 `frozendict` is now version 2.3.5 and everything seems to work just fine with Python 3.10.
