### ISSUE TITLE
how to run archive starknet node?

### ISSUE THREAD

**Issue by zhy827827** [eqlabs/pathfinder#930]
how to run archive starknet node?

**Comment by Mirko-von-Leipzig** [comment]
Pathfinder currently only has an archive mode :) So simply running it does so.

**Comment by zhy827827** [comment]
thank you. full node can queried all history blocks ?

**Comment by Mirko-von-Leipzig** [comment]
Yes, it gives you access to full history. 

In the future we will add options to allow restricting this in order to save disk space, but for now you always get all of history.

**Comment by zhy827827** [comment]
Nice! thank you

**Comment by Mirko-von-Leipzig** [comment]
Awesome :) We should probably add that info to our readme. I'm closing the issue, but feel free to open again if you have other questions.
