### ISSUE TITLE
Transaction max_fee parsing doesn't match JSON RPC API 

### ISSUE THREAD

**Issue by ptisserand** [eqlabs/pathfinder#989]
From my understanding pathfinder assumed that `max_fee` in transaction are encoded with at most 32 digits:
https://github.com/eqlabs/pathfinder/blob/1bc4a6d39c0bc10e35bc21d7a02b23713ed6ee69/crates/rpc/src/v02/types.rs#L85-L86
https://github.com/eqlabs/pathfinder/blob/1bc4a6d39c0bc10e35bc21d7a02b23713ed6ee69/crates/serde/src/lib.rs#L163-L189

But according to JSON RPC API, it should be a FELT:
https://github.com/starkware-libs/starknet-specs/blob/v0.2.1/api/starknet_api_openrpc.json#L1170
https://github.com/starkware-libs/starknet-specs/blob/v0.2.1/api/starknet_api_openrpc.json#L930

**Comment by Mirko-von-Leipzig** [comment]
While the RPC spec allows for `Felt::MAX` (~2^252 minus a bit), the [virtual machine only allows `max = 2^128-1`](https://github.com/starkware-libs/cairo-lang/blob/f260522fe8bcaed187dce2310bb34c0838286748/src/starkware/starknet/definitions/constants.py#L37).

While its probably not the best to disallow this at the deserialisation level, any call with `max_fee > u128::MAX` would fail regardless.

I suppose the error message presented to the caller would not be the best description of the situation.

**Comment by ptisserand** [comment]
I think this check should be done on max fee value and not on length of 'representation'.
If it's ok for you, I can try to fix it.

**Comment by Mirko-von-Leipzig** [comment]
> I think this check should be done on max fee value and not on length of 'representation'. If it's ok for you, I can try to fix it.

You're welcome to give it a try 👍 Feel free to ask for feedback early and often.

**Comment by ptisserand** [comment]
What do you think of removing leading zeros in `visit_str` functions with the following code?:
```rust
fn reduce_str(v: &str) -> String {
    let stripped = v.strip_prefix("0x");
    match stripped {
        None => v.trim_start_matches('0').to_string(),
        Some(s) => {
            "0x".to_owned() + s.trim_start_matches('0')
        }
    }
}
```

**Comment by Mirko-von-Leipzig** [comment]
While your solution would fix the issue, I decided to take another look at this from a codebase perspective which made more changes in #1008.
